### PR TITLE
Added BankingMoneyTranfer

### PR DESCRIPTION
**Pull request by SamarthKadam**
# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes:  #697 

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# Checklist:

- [x] I have made this from my own
- [x] I have taken help from some online resourses 
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK

### CODE REVIEW

**Comment by SamarthKadam** [comment]
@DEEPALI-SUK Please review this

**Review by VidhiBhatt01 — CHANGES_REQUESTED** [review]
image

Can't see anything + update style_links.json

**Comment by SamarthKadam** [comment]
@VidhiBhatt01  please review this

**Comment by DEEPALI-SUK** [comment]
https://deploy-preview-714--amazing-js-projects.netlify.app/bankingmoneytranfer/

**Review by DEEPALI-SUK — CHANGES_REQUESTED** [review]
1. make it responsive
2. add one preview.png in ur folder

**Review by DEEPALI-SUK — APPROVED** [review]

**Review by VidhiBhatt01 — APPROVED** [review]

**Pull request merged**
