### PR TITLE
add points table in read me

### LINKED ISSUE #32: add points Table in Readme
## Issue Type:

[ ] Bug Report
[ ] Feature Request
[x] Documentaion

## **Describe the bug**

- A clear and concise description of what the bug is.

## **Possible solution**

- Describe the solution you thought of.

## **Screenshots**

- If applicable, add screenshots to help explain your problem.
image

### PR DESCRIPTION
**Pull request by rishabhrathore055**
Fixes #32 
# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK
image

### CODE REVIEW

**Comment by ankitapuri** [comment]
I do believe that the points table should be at the bottom , ur views @arpit456jain

**Comment by arpit456jain** [comment]
> I do believe that the points table should be at the bottom , ur views @arpit456jain

No problem @ankitapuri let's see if it looks odd we will create a issue

**Comment by arpit456jain** [comment]
Is it good to be merged ? @ankitapuri if yes then please add labels

**Comment by ankitapuri** [comment]
> Is it good to be merged ? @ankitapuri if yes then please add labels

ohkk cool

**Comment by ankitapuri** [comment]
u can merge then @arpit456jain

**Comment by arpit456jain** [comment]
@rishabhrathore055 do one thing
Delete the forked repo on your GitHub account and then fork it again and always commit on a different branch because i noticed there was some previous commits present

**Comment by rishabhrathore055** [comment]
@arpit456jain okay Thankyou that things I'll keep in mind

**Pull request merged**
