### PR TITLE
Added Flappy Bird game

### PR DESCRIPTION
**Pull request by MarkL50**
# Description

Flappy Bird game is a clone of the original Flappy bird that you can play when you are bored and you have to kill the time. It is created using JavaScript, CSS and Html.

## Type of change

- [x] Added a new project.

# Explain the Testing instructions
 We need to click the left mouse button to make the bird jump and the main focus of the game is to jump through the space between the pillars. The more pillars we get passed through the more score we get which is visible in the bottom side of the page. We have to avoid hitting the pillars, doing that will lead to the game to end and after that a alert message pops up saying our score , and then we can click the left mouse button again to start the game again.

- Operating system: ANY

- Text-editors used: VS Code

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK 

Deployment link :  https://markl50.github.io/Flappy-bird/
<br>
Screenshot (308)

<br>

Screenshot (310)

<br> 
Screenshot (309)

### CODE REVIEW

**Comment by arpit456jain** [comment]
game is good but for me its not user friendly there is very less space for bird and speed is very fast 

ur views @VidhiBhatt01

**Comment by MarkL50** [comment]
> game is good but for me its not user friendly there is very less space for bird and speed is very fast and tbh i don't like theUI
> 
> ur views @VidhiBhatt01


@arpit456jain  I can change the UI and spacing if want me to do that.

**Comment by MarkL50** [comment]
> Indeed, the UI is poor. @MarkL50 can you improve the UI and make the size of bird a little big bigger?

Okay sure @VidhiBhatt01 , I will do the necessary changes ASAP.

**Comment by MarkL50** [comment]
> Indeed, the UI is poor. @MarkL50 can you improve the UI and make the size of bird a little big bigger?

Hey @arpit456jain @VidhiBhatt01 I have made the necessary changes in the flappy bird clone, Please do check it out.

**Comment by arpit456jain** [comment]
https://user-images.githubusercontent.com/55352601/158044335-9db20a6c-e964-4c8e-a3e3-debfaa629bfd.mp4

**Comment by MarkL50** [comment]
> 2022-03-13.09-22-19.mp4

https://user-images.githubusercontent.com/76861726/158046586-fa82acfd-a877-476a-adfc-ba5b68d718c9.mp4

In every pc I have tried this game, I have never faced this issue, I guess there is some error in loading the hole.png file from your end.

**Review by VidhiBhatt01 — COMMENTED** [review]
I am facing the same issue as @arpit456jain .

image

**Comment by MarkL50** [comment]
> I am facing the same issue as @arpit456jain .
> 
> image

Okay I am so sorry @arpit456jain @VidhiBhatt01 ! IDK why but the image that should be used as the gap between the walls was not uploaded. I have uploaded the image and now I think that wont be a problem. Please check it out. :)

**Review by VidhiBhatt01 — COMMENTED** [review]
It's working now. I will just give an honest feedback. The game is glitchy and does not work smoothly. @MarkL50 if you are making something like this for the first time then I must say you did a good job. It meets all the PR requirements, @arpit456jain if you find it feasible you can go on and merge it.

**Comment by MarkL50** [comment]
> It's working now. I will just give an honest feedback. The game is glitchy and does not work smoothly. @MarkL50 if you are making something like this for the first time then I must say you did a good job. It meets all the PR requirements, @arpit456jain if you find it feasible you can go on and merge it. 

Thanks @VidhiBhatt01 , yes it is the first time I am making a game like this I will surely work on making the game more smooth in future.

**Review by astha2412 — COMMENTED** [review]
Facing the same issue as @arpit456jain @VidhiBhatt01

**Comment by arpit456jain** [comment]
#333

**Pull request merged**
