### PR TITLE
15 puzzle Challenge added

### PR DESCRIPTION
**Pull request by Sabarinathan07**
# Description

The 15 puzzle challenge works completely fine. It doesn't break any part of the project. Tech Stack used: HTML, CSS, Js. I have uploaded the screenshot after adding my project. Please merge my pull request! Thanks!!!

Fixes:  #513 

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# Checklist:

- [x] I have made this from my own
- [x] I have taken help from some online resourses 
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK
Screenshot 2022-04-21 at 8 56 08 PM
Screenshot 2022-04-21 at 8 56 15 PM

And Please add GSSoC22 tag!

### CODE REVIEW

**Review by VidhiBhatt01 — CHANGES_REQUESTED** [review]
1. Add readme file and explain how to play the game.
2. The size is very small on small screens. Fix it.

image


Lastly, are you sure you made it totally on your own?

**Comment by VidhiBhatt01** [comment]
https://deploy-preview-526--amazing-js-projects.netlify.app/15-puzzle-challenge/

**Comment by Sabarinathan07** [comment]
yeah sure! Working on it!

**Comment by Sabarinathan07** [comment]
<p align="center" >

&nbsp; &nbsp;

</p>

Screenshot 2022-04-23 at 11 05 06 PM


Screenshot 2022-04-23 at 11 05 09 PM

## Changes have been made! please review @VidhiBhatt01

**Comment by Sabarinathan07** [comment]
Do I need to change anything more @VidhiBhatt01?

**Review by astha2412 — COMMENTED** [review]
LGTM!!

**Review by arpit456jain — APPROVED** [review]

**Pull request merged**
