### PR TITLE
Lyricz... API implemented website

### PR DESCRIPTION
**Pull request by yash-25log**
# Description

An API implemented lyrics finder
just added and implemented api
haven't built homepage yet
more suggestion going to implment in future-
banner
music player and more

Fixes:  #(issue no.)
#581 

# Checklist:

- [x] I have made this from my own
- [x] I have taken help from some online resourses(just to implement API) 
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK
image

image

responsive-
image
image

### CODE REVIEW

**Comment by yash-25log** [comment]
https://lyric-z.vercel.app/
@VidhiBhatt01

**Comment by yash-25log** [comment]
@VidhiBhatt01 @arpit456jain @DEEPIKA-SUK @DEEPALI-SUK

**Review by VidhiBhatt01 — COMMENTED** [review]
image

image

Does this work for Bollywood songs?

**Comment by VidhiBhatt01** [comment]
https://deploy-preview-585--amazing-js-projects.netlify.app/lyricz%20api%20lyrics%20finder/

**Review by VidhiBhatt01 — CHANGES_REQUESTED** [review]
Add the project in style_links.json

**Comment by yash-25log** [comment]
> image
> 
> image
> 
> Does this work for Bollywood songs?

nope it doesn't work for Bollywood songs
i didn't made API
it's public and not of India
it perfectly works with english

**Comment by yash-25log** [comment]
> 

i didn't undderstand this 
what exactly is style_link json referring here?

**Comment by yash-25log** [comment]
> Add the project in style_links.json


i didn't undderstand this
what exactly is style_link json referring here?

**Comment by yash-25log** [comment]
@VidhiBhatt01 done
found the file you meant in the repo

**Comment by yash-25log** [comment]
image
works fine with any english song

**Comment by yash-25log** [comment]
@arpit456jain Krdo bhai

**Comment by arpit456jain** [comment]
In mobile view horizontal scrolling is not much effective
Can it be vertical scrolling?

**Comment by yash-25log** [comment]
> In mobile view horizontal scrolling is not much effective Can it be vertical scrolling?

It can be but then lyrics will go very down or I will have to make it on new tab

**Comment by yash-25log** [comment]
This is because it suggest songs with same name

**Comment by yash-25log** [comment]
For now you may merge I am thinking of adding banners and more elements as there is no point of leaving it empty

**Comment by yash-25log** [comment]
Will make a note of your suggestion

**Pull request merged**
