### PR TITLE
Added the random color generator documents

### PR DESCRIPTION
**Pull request by stutimohta20**
# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes:  #655 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [x] I have made this from my own
- [x] I have taken help from some online resourses 
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK
image

### CODE REVIEW

**Comment by stutimohta20** [comment]
@DEEPALI-SUK Please review

**Review by VidhiBhatt01 — COMMENTED** [review]
@arpit456jain pls help with the deploy link

**Comment by VidhiBhatt01** [comment]
> > @arpit456jain pls help with the deploy link
> 
> can i help with it, does it hold some points??

It's an internal error, we will fix it dw

**Comment by arpit456jain** [comment]
@stutimohta20  make this PR again hope it will host it now

**Comment by arpit456jain** [comment]
@stutimohta20  if possible host it on github and share its link in next PR as backup or upload the code on google drive and share its link

**Pull request closed without merging**
