### PR TITLE
background-Changer-Modification

### LINKED ISSUE #323: Background color changer
## Issue Type:

- [ ] Bug Report
- [y ] Feature Request
- [ ] Documentaion

## **Describe the bug**

-There is not any bug, i want enhance the UI . It is looking like old website, colors can be enhanced. Just see the screenshot, i can enhance it and make it much better.

## **Possible solution**

- I will add mix colors or different background ,so, that it will look very nice,

## **Screenshots**

- 
Screenshot 2022-03-07 123723

### PR DESCRIPTION
**Pull request by mayank-del**
# Description

You can see on sceenshot also, that I have added 8 colors instead of four ,they are no more colors,  they became beautiful linear-gradients, Similarly I made Blog post Heading animated ,  Heading's color will automatically change and cause glow effect  as well .

Fixes #323

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [y ] New feature (non-breaking change which adds functionality)

# Explain the Testing instructions

**Test Configuration**:

- Operating system:
- Version:
- Text-editors used:

# Checklist:

- [y] My code follows the style guidelines of this project
- [ y] I have performed a self-review of my own code
- [y ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [y ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merge
- [ ] 
Before Change screenshot

Screenshot 2022-03-07 123723
d and published in downstream modules

After changes Screenshot

Screenshot 2022-03-09 084603

### CODE REVIEW

**Comment by arpit456jain** [comment]
make it responsive @mayank-del

**Comment by mayank-del** [comment]
Ok , I will do it soon

**Comment by mayank-del** [comment]
@arpit456jain  sir , i made it responsive, as told by you. Now, it's fine.

**Comment by VidhiBhatt01** [comment]
Hey @mayank-del you have successfully made it responsive! Can you make one more change?
image
In the image as you can see, the words Blog Post are not visible clearly, can you change its styling please?

**Review by VidhiBhatt01 — CHANGES_REQUESTED** [review]
Hey @mayank-del you have successfully made it responsive! Can you make one more change?
image
In the image as you can see, the words Blog Post are not visible clearly, can you change its styling please?

**Comment by mayank-del** [comment]
Now see @VidhiBhatt01 maam , I fixed that part as well. Now,I think  it would be ok.

**Comment by VidhiBhatt01** [comment]
Now I can't find it on the deployed link. @arpit456jain can you help?

**Comment by mayank-del** [comment]
What happened @VidhiBhatt01  ??

**Review by arpit456jain — APPROVED** [review]

**Pull request merged**
