### PR TITLE
added spotify clone

### LINKED ISSUE #277: Add a spotify clone
## Issue Type:

- [ ] Bug Report
- [ ] Feature Request
- [ ] Documentaion

## **Describe the bug**

- A clear and concise description of what the bug is.

## **Possible solution**

- Describe the solution you thought of.

## **Screenshots**

- If applicable, add screenshots to help explain your problem.

### PR DESCRIPTION
**Pull request by ManaliPawar**
# Description

This is a Spotify Clone, having a similar interface as of the app and plays music.

Fixes #277 

This is issue no #277 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Explain the Testing instructions

**Test Configuration**:

- Operating system:
- Version:
- Text-editors used:

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK
Un

### CODE REVIEW

**Comment by ManaliPawar** [comment]
maam i have increased the spacing of play button. For the responsive one,I will try it

**Comment by arpit456jain** [comment]
@ManaliPawar its not responsive yet try to make it responsive take ur time 

if its not responsive - > level2
if its responsive - > level3

**Comment by VidhiBhatt01** [comment]
@ManaliPawar

**Comment by ManaliPawar** [comment]
I have increased the spacing but not able to make it responsive ma'am

**Comment by VidhiBhatt01** [comment]
BTW you have'nt pushed the changes, spacing is still the same.

**Comment by ManaliPawar** [comment]
Ok ma'am

**Comment by ManaliPawar** [comment]
Will do it today itself.

**Pull request merged**
