### PR TITLE
Shooter game

### PR DESCRIPTION
**Pull request by Jackson93150**
# Description

Here is the game , i’m still a junior developer so the code can be a bit messy and poorly optimized , and the game is kinda heavy in weight sorry for that 🙏🏽  

Fixes:  #[425](https://github.com/arpit456jain/Amazing-Js-Projects/issues/425)

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK

The game is already deployed in this link ⬇️ 
https://jackson93150.github.io/JsGame/

### CODE REVIEW

**Review by astha2412 — APPROVED** [review]

**Comment by astha2412** [comment]
Screenshot (425)
After pressing E button, no function is working?

**Comment by astha2412** [comment]
Rest is fine @Jackson93150, Game is Amazing!

**Comment by Jackson93150** [comment]
you need to be on the new weapon box and press e and game will continue
unknown (1)

**Review by VidhiBhatt01 — APPROVED** [review]
@Jackson93150 Are you sure you made it totally on your own? 👀

**Review by VidhiBhatt01 — COMMENTED** [review]
Also, add this project in style_links.json

**Comment by Jackson93150** [comment]
@VidhiBhatt01 yes it was a project that i made this year for my video gaming programmation course .
You can see my progress in this project on the original repository here : https://github.com/Jackson93150/JsGame
And i took a base from a similar game that i programmed past year but in Rust here : https://github.com/Jackson93150/RetroRunner-

**Comment by arpit456jain** [comment]
@Jackson93150 the game is quite impressive can you do some changes

w->up
a->left
d->right

**Comment by Jackson93150** [comment]
@arpit456jain you mean to change to QWERTY so up -> w , left -> a , down -> s and right -> d ?

**Comment by Jackson93150** [comment]
well it is changed now 👍🏽

**Comment by arpit456jain** [comment]
@Jackson93150 ur project is very heavy can u decrease the size of images take help from mentors

**Comment by arpit456jain** [comment]
https://deploy-preview-427--amazing-js-projects.netlify.app/2dshootergame/

**Comment by Jackson93150** [comment]
@arpit456jain i resized and compressed from 60+mb to 23mb is it enough ?

**Review by arpit456jain — APPROVED** [review]

**Pull request merged**
