### PR TITLE
Added Image-Resizer Website/App

### LINKED ISSUE #274: Add Image Resizer App
## Description

Hey! Arpit,
I would like to make an Image Resizer App.
- User can upload images of any ratio.
- Resize them with or without maintaining the aspect ratio.
- And just click to download.

I am a GSSoC22 participant, and would like to work on this project and contribute to this repository!
Please assign this project to me!

### PR DESCRIPTION
**Pull request by itaintkevin**
# Description

Added an Image Resizer Website, that can resize images uploaded from your system.
There are no major dependencies for using this Website and it can be accessed online at https://itaintkevin.github.io/Image-Resizer.
**To access the website in your local system, the HTML, CSS AND JS files should be present and the index.html file should be opened using a "Live Server" to see realtime changes.**

Fixes #274

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Explain the Testing instructions

**Test Configuration**:

- Operating system: All
- Version: Any
- Text-editors used: Visual Studio Code

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK

https://itaintkevin.github.io/Image-Resizer

### CODE REVIEW

**Review by VidhiBhatt01 — CHANGES_REQUESTED** [review]
image

Can you fix the overlapping?

**Comment by itaintkevin** [comment]
@VidhiBhatt01 Yeah on it.

**Comment by itaintkevin** [comment]
Hey! @VidhiBhatt01, I have made some changes. 
Sorry for the inconvenience. Pls, do have a look.

**Comment by itaintkevin** [comment]
Hi @VidhiBhatt01, Just a reminder, I have made the changes requested 4 days back. Please check when you are free. Thank you.

**Review by VidhiBhatt01 — APPROVED** [review]

**Comment by VidhiBhatt01** [comment]
I somehow missed the message. Sorry for the delay. From next time, you can send the PR link to the discord server if it takes more than 48 hours.

**Pull request merged**
