### PR TITLE
Added Circular Timer

### PR DESCRIPTION
**Pull request by Anirban-1490**
# Description

Added a Circular Timer made in HTML,CSS and JS

Fixes:  #648 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [x] I have made this from my own
- [ ] I have taken help from some online resourses 
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK

https://user-images.githubusercontent.com/82874704/168123128-fcf932d8-a4e0-441b-82a2-50effbaec749.mp4

### CODE REVIEW

**Review by VidhiBhatt01 — APPROVED** [review]
Can we add more functionality to this? Like the user will enter/pick a time from given options and then the timer will work accordingly. We will increase the level by 1 if you can do so. Let us know whether you want to keep it as it is or add the above feature : )

**Comment by Anirban-1490** [comment]
> Can we add more functionality to this? Like the user will enter/pick a time from given options and then the timer will work accordingly. We will increase the level by 1 if you can do so. Let us know whether you want to keep it as it is or add the above feature : )

ok working on it

**Comment by Anirban-1490** [comment]
@VidhiBhatt01 please check now. i have done the changes

**Review by VidhiBhatt01 — APPROVED** [review]
Awesome!!

**Comment by Anirban-1490** [comment]
> Awesome!!

Thank you :)

**Pull request merged**
