### PR TITLE
Certificate Generator added

### PR DESCRIPTION
**Pull request by itzwow**
# Description

Added a certificate generator website. The certificate will be generated once we enter our name in the input field.

Fixes:  #508 

## Type of change

- [ x] New feature (non-breaking change which adds functionality)

# Checklist:

- [ x] I have taken help from some online resources 
- [x ] My code follows the style guidelines of this project
- [ x] I have performed a self-review of my own code
- [ x] My changes generate no new warnings

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK:
cert

### CODE REVIEW

**Comment by itzwow** [comment]
This is the unbroken URL:
https://deploy-preview-523--amazing-js-projects.netlify.app/certificate%20generator

**Review by VidhiBhatt01 — CHANGES_REQUESTED** [review]
I think there are some extra files in this PR, remove them and add this project in style_links.json.

Btw the website is good but do you think it will be useful? As one cannot change the details of the certificate.

**Comment by arpit456jain** [comment]
@itzwow remove unnecessary files rest all is good
can we change the certificate template ?

**Comment by itzwow** [comment]
> @itzwow remove unnecessary files rest all is good can we change the certificate template ?
 
@arpit456jain 
Can you kindly give me 3-4 days time I can work upon the template thing after that , Currently I am having my end sem exams going on :|

**Comment by VidhiBhatt01** [comment]
Cool

**Comment by itzwow** [comment]
@arpit456jain  
-Removed the unnecessary files 
- added the template options and a dropdown to select template from it
-
certificate web

Kindly review the changes

**Review by VidhiBhatt01 — CHANGES_REQUESTED** [review]
Everything is perfect just make it properly responsive!

image

**Comment by arpit456jain** [comment]
@itzwow ur work is great 

i was actually asking like if i want to add my template is it possible.

**Comment by itzwow** [comment]
> Everything is perfect just make it properly responsive!
> 
> image

> Now it is responsive
Capture

**Comment by itzwow** [comment]
> @itzwow ur work is great
> 
> i was actually asking like if i want to add my template is it possible.


@arpit456jain  We can add new templates by modifying the code but we can't add template from user end.
whatever template we want we need to add in the code folder and then we can use  it .

**Comment by arpit456jain** [comment]
ok great

**Pull request merged**
