### PR TITLE
added the card matching game to project

### PR DESCRIPTION
**Pull request by prer45**
# Description

I have made the card matching game project using HTML,CSS,JS. The game works according to the functionality mentioned earlier.

# Checklist:

- [x] I have taken help from some online resourses 
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK
card-ss

### CODE REVIEW

**Comment by DEEPALI-SUK** [comment]
@prer45 u have copied the code from here
 https://youtu.be/28VfzEiJgy4
you are allowed to take reference but not allowed to copy word to word

**Review by DEEPALI-SUK — COMMENTED** [review]
u have also not linked the original issue

**Comment by arpit456jain** [comment]
> > @prer45 u have copied the code from here https://youtu.be/28VfzEiJgy4 you are allowed to take reference but not allowed to copy word to word
> 
> Yes I referred that video but will it be okay if i make some changes to the UI?

yes improve its UI and make it responsive

**Review by VidhiBhatt01 — COMMENTED** [review]
@prer45 in how many days can you update the UI?

**Pull request closed without merging**
