### PR TITLE
Added a project which uses vanilla javascript to create a type writing effect in a webpage.

### PR DESCRIPTION
**Pull request by JSM313**
Added a new project.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Explain the Testing instructions

**Test Configuration**:

- Operating system:
- Version:
- Text-editors used:

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK

### CODE REVIEW

**Review by VidhiBhatt01 — CHANGES_REQUESTED** [review]
Fill the PR description properly

**Comment by JSM313** [comment]
> Fill the PR description properly

I have made the changes, please review it.

**Comment by arpit456jain** [comment]
@JSM313 link the issue

**Comment by arpit456jain** [comment]
https://deploy-preview-406--amazing-js-projects.netlify.app/typewriter%20effect/

**Comment by arpit456jain** [comment]
> A new user left a comment. This user must be approved by a Netlify team owner before comments can be displayed.
> 
> [Approve this user](https://app.netlify.com/teams/arpit456jain/reviewers)

@JSM313 ??

**Comment by JSM313** [comment]
> @JSM313 from next time create a issue first and then PR

Hi arpit, 
My sincere Apologies for the inconvenience caused, actually it is my very first contribution, I am very much new to this issue, thank you for your help and for your feedback.

From next time I will take all these things into consideration.

Thank you

**Pull request merged**
