### PR TITLE
Add Drum Kit

### PR DESCRIPTION
**Pull request by ri-tae-ka**
Added Drum Kit Website that allows user to play drum beats by clicks or either key presses.

### CODE REVIEW

**Comment by ankitapuri** [comment]
@ri-tae-ka attach Screenshots here

**Comment by ri-tae-ka** [comment]
Screenshot 2021-07-15 131257

This is a responsive drum kit and will allow to play sounds using key presses or clicks on buttons.

**Comment by ankitapuri** [comment]
@ri-tae-ka , r u sure u have not downloaded the code because the same template is available across the web without any changes

**Comment by ri-tae-ka** [comment]
No this was made by me entirely in march 2021 if you need I can surely add some changes to it.

**Comment by ri-tae-ka** [comment]
Screenshot 2021-07-15 135202

Should i change the code a little to add personalization to it.

**Comment by ankitapuri** [comment]
Yes

**Comment by ri-tae-ka** [comment]
Kindly check the updates.

**Comment by arpit456jain** [comment]
@ankitapuri

**Review by ankitapuri — APPROVED** [review]

**Comment by ankitapuri** [comment]
@arpit456jain u can merge it

**Comment by ri-tae-ka** [comment]
Should i fill up my username for Github ID in the form provided?

**Comment by arpit456jain** [comment]
> Should i fill up my username for Github ID in the form provided?

Yes

**Pull request merged**
