### PR TITLE
Voice To Text Converter

### PR DESCRIPTION
**Pull request by Sukriti-m**
# Description

I have made a Voice to Text Converter using HTML, CSS and JS.

Fixes:  #554 

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# Checklist:

- [x] I have made this from my own
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK

https://user-images.githubusercontent.com/93239528/166140855-fb1ff466-2c3f-4f76-9800-84fe57f74b94.mp4

please review this PR. @arpit456jain  @VidhiBhatt01

### CODE REVIEW

**Review by VidhiBhatt01 — CHANGES_REQUESTED** [review]
1. Sizing is very small. Make it properly responsive for all screen sizes.
image

2.Add this project in style_links.json

3. Did you make it totally on your own?? If not, add the resources you referred in a readme file

**Comment by VidhiBhatt01** [comment]
https://deploy-preview-586--amazing-js-projects.netlify.app/voice%20to%20text%20converter/

**Comment by Sukriti-m** [comment]
I have made the required changes. Please review it. @DEEPALI-SUK @VidhiBhatt01

**Review by DEEPALI-SUK — APPROVED** [review]

**Comment by DEEPALI-SUK** [comment]
@Sukriti-m u have made it on your own?

**Comment by Sukriti-m** [comment]
> @Sukriti-m u have made it on your own?

I have mentioned the resources in the README.md file from where I took the help.

**Review by DEEPALI-SUK — APPROVED** [review]

**Pull request merged**
