### PR TITLE
Added CodeKaro Website

### PR DESCRIPTION
**Pull request by Abh1shekSingh**
Codekaro is a website where you can see the list of all the future competitive coding contest helding in future. Basically its is you consistency partner

here is the live link to the website: https://codeekaro.netlify.app/

Fixes:  #463 

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# Checklist:

- [x] I have made this from my own
- [x] I have taken help from some online resourses 
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK

### CODE REVIEW

**Review by VidhiBhatt01 — CHANGES_REQUESTED** [review]
@arpit456jain deployed link pe nothing is visible. Aby idea why so ?
image

@Abh1shekSingh I checked it from the deploy link that you attached in the PR description

1. You need to make it responsive

image

2. I think the size of all the boxes must be the same.

image


 3. Add this project in style_links.json

**Comment by Abh1shekSingh** [comment]
The size of all boxes can't be the same because I created dynamic cards. if
i make a fixed size by any way, it will surely distor others.

**Comment by Abh1shekSingh** [comment]
Done all the changes

**Comment by arpit456jain** [comment]
@Abh1shekSingh is this a react app ?

**Comment by arpit456jain** [comment]
@Abh1shekSingh sorry but we are not accepting react projects if u could made this type of thing on a simple one page with vanilla js it would be great

**Comment by Abh1shekSingh** [comment]
Haa mein vaise bhi yeh issue close krne wala tha, reason aapko btaya Hi tha
mene kal. So koi baat nhi.

**Pull request closed without merging**
