### PR TITLE
Movie-Search-App

### PR DESCRIPTION
**Pull request by Atif0604**
# Description
Added Movie Search App

Fixes # (issue no.)

Movie Search App #64

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# Explain the Testing instructions

**Test Configuration**:

- Operating system:
- Version:
- Text-editors used:

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK

### CODE REVIEW

**Comment by Atif0604** [comment]
hey @arpit456jain 
please review my pr

**Comment by arpit456jain** [comment]
@Atif0604 you made it yourself  ?

**Comment by Atif0604** [comment]
> @Atif0604 you made it yourself ?

yes @arpit456jain i made it myself
i wasn't able to contribute before because i was making many different mini projects for the contribution

**Comment by arpit456jain** [comment]
Great work @Atif0604 🔥🔥

**Comment by Atif0604** [comment]
@arpit456jain 
will be contributing more to repo 😊

**Pull request merged**
