### PR TITLE
added T-rex runner game

### PR DESCRIPTION
**Pull request by RAHULBAWA777**
added T-rex runner game (with additional functionalities)

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes:  #(455)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [x] I have made this from my own
- [x] I have taken help from some online resourses 
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

# ATTACH SCREEN-SHOTS 
Screenshot (275)

DEPLOYMENT LINK - https://rahulbawa777.github.io/T-Rex-Runner-game-/

### CODE REVIEW

**Comment by arpit456jain** [comment]
@RAHULBAWA777 make it responsive

**Review by VidhiBhatt01 — COMMENTED** [review]
@RAHULBAWA777

**Comment by RAHULBAWA777** [comment]
> @RAHULBAWA777 make it responsive did u make it from ur own ? if not mention the resource

Yes made it of my own.... Just took the reference of basic game functionality from yt.... Rest all the work and pictures used are by me

**Comment by RAHULBAWA777** [comment]
I don't know how to make it responsive as it only works with pixels.... The
game won't work if I use rem Or em or something else....

**Review by VidhiBhatt01 — CHANGES_REQUESTED** [review]
When you open, you see a blank screen.
image
Then you scroll down and see this
image
And then at the end
image


1. Fix it, all things must be visible without scrolling only. 

2. Add links to the resources you referred to by adding a readme file.

3. Add this project in style_links.json

**Pull request closed without merging**
