### PR TITLE
Pokemon Generator files added

### LINKED ISSUE #348: Add a Pokemon Generator
## Issue Type:

- [x] Feature Request

## **Describe the feature**

- I wish to add a Pokemon Generator which uses free Pokemon API.
- Live site: https://adit0507.github.io/Pokemon-Card-Generator/

## **Possible solution**

- Describe the solution you thought of.

## **Screenshots**
Pokemon

### PR DESCRIPTION
**Pull request by Adit0507**
# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes #348 

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# Explain the Testing instructions

**Test Configuration**:

- Operating system: Windows 10
- Version: Latest Chrome version
- Text-editors used: Visual Studio Code

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK

### CODE REVIEW

**Review by VidhiBhatt01 — COMMENTED** [review]
This is 100% copied. Do you want to say anything in clarification @Adit0507?

https://www.youtube.com/watch?v=_JUSpgchD1I

**Comment by Adit0507** [comment]
> This is 100% copied. Do you want to say anything in clarification @Adit0507?
> 
> https://www.youtube.com/watch?v=_JUSpgchD1I

Yes I had referred to this tutorial for making this and it could be a good addition to this project.
I had already made this project before though. 
Can this really be considered plagiarism since most of the projects are taken from some place or the other ?
Do you wish to see the Repo I had made for this project?

**Comment by Adit0507** [comment]
At the end of the day the objective of this project is to help beginners with JS. Since this project wasn't present here I wanted to add it.
Now if you have more problem with this, you may close the PR

**Comment by VidhiBhatt01** [comment]
Yes but plagiarism is strictly not allowed. You could have taken the inspiration from the video and made some changes on it/changed the theme. It's unfair to the one who originally created it. I was personally very excited for this PR but seeing it plagiarized makes me highly disappointed. We are constantly working and rechecking all the PRs which have plagiarised code. If you want to assist us in this process let us know. @arpit456jain what are your views on this?

**Comment by Adit0507** [comment]
> Yes but plagiarism is strictly not allowed. You could have taken the inspiration from the video and made some changes on it/changed the theme. It's unfair to the one who originally created it. I was personally very excited for this PR but seeing it plagiarized makes me highly disappointed. We are constantly working and rechecking all the PRs which have plagiarised code. If you want to assist us in this process let us know. @arpit456jain what are your views on this?

This is not plagiarism first of all, most of the projects aren't original here. If a person wants to learn how to make a project he/she will take it from somewhere right and the aim of this project is to provide a good collection of JS projects so the student doesn't waste their time looking for resources. 

Now I didn't copy-paste the  whole code (btw I did make minor changes in the theme) if that's what u think I did, I already had this project ready and I thought it would be a good addition, so I wished to contribute. Rest is upto you

**Comment by arpit456jain** [comment]
@Adit0507 if u have taken refer from any tutorial then u should mention it in PR.
i am merging this time but from next time if u refer from any yt video then mention it with its url
if we find it plagiarized we will not accept it.

**Pull request merged**
