### PR TITLE
birthday-countdown-bug #316

### LINKED ISSUE #316: Birthday countdown, year is not generalized ,So no countdown is coming ,I can fix this within a small amount of time, can  I work on it? please assign me in this
## Issue Type:

- [Y] Bug Report
- [ ] Feature Request
- [ ] Documentaion

## **Describe the bug

A particular year is given which 2021,year is not generalized ,So no countdown is coming

## **Possible solution**
I can generalize the year ,So that it will work  for every year.

## **Screenshots**

- If applicable, add screenshots to help explain your problem.
birthday countdown issue

### PR DESCRIPTION
**Pull request by mayank-del**
# Description

there was a bug in  in birthday countdown that that year was a particular year ,so countdown shows no dates, I generalized  it , So that , you do not have to change it every year. 
  
fixes #316

### CODE REVIEW

**Comment by VidhiBhatt01** [comment]
did you create an issue for this? If yes link that in the PR description. If not then create one and then raise the PR

**Comment by mayank-del** [comment]
I raised the Issue few minutes after , I am new to open source ,sorry for that, I am again raising PR.

**Comment by VidhiBhatt01** [comment]
Wait

**Comment by VidhiBhatt01** [comment]
just edit the PR description and link the issue

**Comment by mayank-del** [comment]
Ok Maam

**Review by VidhiBhatt01 — APPROVED** [review]

**Pull request merged**
