### PR TITLE
Simple Library Management

### PR DESCRIPTION
**Pull request by samipak458**
# Description

A simple Library Management Project which is easy to use and understand as a beginner.
This Project is very helpful in understanding the concept of Local Storage and search the book by name of book, author and type. I make this project with the help of HTML, CSS, Bootstrap & JavaScript.

Fixes:  #616 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [x] I have made this from my own
- [x] I have taken help from some online resourses 
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK
image

### CODE REVIEW

**Comment by samipak458** [comment]
@DEEPALI-SUK @arpit456jain kindly review my PR.

**Comment by DEEPALI-SUK** [comment]
https://deploy-preview-628--amazing-js-projects.netlify.app/simple%20libray%20management/

**Review by DEEPALI-SUK — CHANGES_REQUESTED** [review]
image

1. not responsive
2. add image folder inside main root folder

**Comment by samipak458** [comment]
All requested changes has been completed. Kindly review again @DEEPALI-SUK

**Review by DEEPALI-SUK — CHANGES_REQUESTED** [review]
image

delete this image folder

**Comment by samipak458** [comment]
Done, kindly review and merge it @DEEPALI-SUK. Thank you

**Review by DEEPALI-SUK — APPROVED** [review]

**Review by VidhiBhatt01 — CHANGES_REQUESTED** [review]
image
Everything is fine, it's just that the text at the end is getting cut. Fix that please

**Comment by arpit456jain** [comment]
@samipak458 i know u made this by watching code with harry 
and its fine 
but improve the UI only then i will merge

**Comment by samipak458** [comment]
@arpit456jain Done! kindly review and merge it. Thank you

**Review by VidhiBhatt01 — CHANGES_REQUESTED** [review]
Merge conflicts still need to be resolved

**Comment by samipak458** [comment]
@VidhiBhatt01 I'm unable to resolve merge conflict. Should I create new pull request ?

**Comment by VidhiBhatt01** [comment]
Resolved!

**Review by VidhiBhatt01 — APPROVED** [review]

**Pull request merged**
