### PR TITLE
Meme Generator

### LINKED ISSUE #213: Adding A Meme Generator
## Issue Type:

- [x] Feature Request
- [x] Documentation

## **Describe the bug**

- New feature, not a bug.

## **Possible solution**

- Generate memes based on what images users upload and also the corresponding text, and also provide functionality for saving and downloading them.

## **Screenshots**

- If applicable, add screenshots to help explain your problem.

images

### PR DESCRIPTION
**Pull request by pragmatic-philosopher09**
# Description

Created a meme generator tool in HTML, CSS & JS!

Fixes #213 

## Type of change

- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

# Explain the Testing instructions

**Test Configuration**:

- Operating system: Windows
- Version: 10
- Text-editors used: VSCode

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK

Meme1

Meme3

My Meme

### CODE REVIEW

**Review by VidhiBhatt01 — CHANGES_REQUESTED** [review]
Remove Expanding Flex cards files from the PR.

**Comment by VidhiBhatt01** [comment]
Also, I thought that you will make something like a user enters a keyword and you generate multiple memes on it from which he/she can choose one. The one you made is very simple. This can be done using any editing software. Why would someone use this tool? 😅

**Comment by pragmatic-philosopher09** [comment]
> Also, I thought that you will make something like a user enters a keyword and you generate multiple memes on it from which he/she can choose one. The one you made is very simple. This can be done using any editing software. Why would someone use this tool? 😅

Actually, I was focussing on a simplistic, minimal application of JS, and hence, wasn't thinking along those lines. But, with time, I do intend to improve and spruce up that feature, which would likely incorporate some additional tech stack probably 😁😅...

**Comment by VidhiBhatt01** [comment]
> > Also, I thought that you will make something like a user enters a keyword and you generate multiple memes on it from which he/she can choose one. The one you made is very simple. This can be done using any editing software. Why would someone use this tool? 😅
> 
> Actually, I was focussing on a simplistic, minimal application of JS, and hence, wasn't thinking along those lines. But, with time, I do intend to improve and spruce up that feature, which would likely incorporate some additional tech stack probably 😁😅...

Awesome!!

**Pull request merged**
