### PR TITLE
Add game of pong

### PR DESCRIPTION
**Pull request by tanktejas**
**Checklist:**
 I have made this from my own
 I have taken help from some online resourses
 My code follows the style guidelines of this project
 I have performed a self-review of my own code
 I have commented my code, particularly in hard-to-understand areas
 I have made corresponding changes to the documentation
 My changes generate no new warnings

**Description** 
 => I have added the solution to issue #459 
=> by below the image you can see what the game looks like.
=> point are changing dynamically.

=> one player playing with the computer.

**Photos** 

Screenshot (227)

### CODE REVIEW

**Review by VidhiBhatt01 — CHANGES_REQUESTED** [review]
1. Add a readme file and mention how to play this game there.
2. Make it responsive for all screen sizes.

image

3.  Try making it more smooth and improve the UI if possible.

**Comment by VidhiBhatt01** [comment]
Also add this project in style_links.json

**Comment by tanktejas** [comment]
Yes,
I have added a Readme file for game instruction.
I have made site responsive.
also added link in style_links.json.

Now, is it fine ??

**Comment by tanktejas** [comment]
If there are no changes then Could you merge this PR Now ??

**Review by VidhiBhatt01 — APPROVED** [review]

**Comment by tanktejas** [comment]
Is it ok to merge ???

**Comment by astha2412** [comment]
> Is it ok to merge ???

Yes

**Review by DEEPIKA-SUK — APPROVED** [review]

**Pull request merged**
