### PR TITLE
Added Car Racing Game

### PR DESCRIPTION
**Pull request by itsmohitnamdeo**
## Type of change

- [ ] Added Car Racing JS Game 

# Checklist:

- [ ] I have taken help from some online resourses 
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings

### CODE REVIEW

**Review by VidhiBhatt01 — CHANGES_REQUESTED** [review]
Fill the PR template properly and link the issue in PR description

**Comment by itsmohitnamdeo** [comment]
> @itsmohitnamdeo u made this from ur own ?

No , I will take help from other sources..

**Comment by itsmohitnamdeo** [comment]
I will take help from the other online  resources..

**Comment by itsmohitnamdeo** [comment]
> @itsmohitnamdeo u made this from ur own ?

@arpit456jain I take some help from the other online resources...

**Comment by itsmohitnamdeo** [comment]
> Fill the PR template properly and link the issue in PR description

Car Racing Game
#454 

It is a simple project developed using js, HTML and CSS. This system provides the beautiful interface of a gaming system.

**Review by VidhiBhatt01 — COMMENTED** [review]
Again you raised the PR without the issue being assigned 🤦‍♀️

**Comment by itsmohitnamdeo** [comment]
> Again you raised the PR without the issue being assigned 🤦‍

**Pull request closed without merging**
