### PR TITLE
Sort projects

### LINKED ISSUE #358: Sort the Projects
Arrange the projects in a sequential way ( The way they are shown in GitHub). Changes are needed to be made in style_links.json.

image

### PR DESCRIPTION
**Pull request by mrkc2303**
# Description

As mentioned in the issue i have made changes and sorted the project in style_links.json file. 

Fixes #358 

## Type of change

- [x] This change requires a documentation update

# Explain the Testing instructions

**Test Configuration**:

- Operating system: ANY
- Version: ANY
- Text-editors used: VS CODE

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK

### CODE REVIEW

**Comment by mrkc2303** [comment]
Hey @VidhiBhatt01 @DEEPALI-SUK 

Kindly review the PR and check if any changes are required?

Thanks

**Comment by DEEPALI-SUK** [comment]
@mrkc2303 there are unnecessary files in the commits please update your PR.

**Comment by mrkc2303** [comment]
@DEEPALI-SUK Thats may be because of my PR #361 
Kindly let me know what can i do?

**Comment by VidhiBhatt01** [comment]
You need to delete all unwanted files. If you have raised any PR previously from the same branch then use a different one for this PR.

**Comment by mrkc2303** [comment]
For the same issue i will open another PR and resolve the errors. 
I am closing this for the same

**Pull request closed without merging**
