### PR TITLE
Added Sum of Digits

### PR DESCRIPTION
**Pull request by eswarbhageerath**
This is the PR of the issue  Sum Of Digits Caluclator #518 
please review it
Thank you Sir

### CODE REVIEW

**Review by VidhiBhatt01 — CHANGES_REQUESTED** [review]
1. Resize it so that we don't need to scroll.
2. Add it in style_links.json

image

**Comment by eswarbhageerath** [comment]
@VidhiBhatt01 I have made the changes "removed scroll and centered  the contents" and "added this file details in style_links.json"

Please review this PR sir...Thank you

**Review by VidhiBhatt01 — APPROVED** [review]
https://deploy-preview-520--amazing-js-projects.netlify.app/sum%20of%20digits%20caluclator/sum

**Comment by eswarbhageerath** [comment]
@VidhiBhatt01 Please review my PR

**Comment by eswarbhageerath** [comment]
@arpit456jain Please review my PR

**Comment by eswarbhageerath** [comment]
@arpit456jain @VidhiBhatt01 Please merge this PR. for the issue Sum Of Digits Caluclator #518

**Pull request merged**
