### PR TITLE
Spotify clone added

### PR DESCRIPTION
**Pull request by BrownCoderAyush**
# Description

I added a spotify clone having wide variety of features and nice UI .

Fixes:  #530 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [x] I have taken help from some online resourses 
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK
Screenshot (18)

### CODE REVIEW

**Review by VidhiBhatt01 — CHANGES_REQUESTED** [review]
image


1.  Add some spacing
2.  Make the size small so that it stays within the box. If feasible, border radius 50% karke circle bana do image ko
3. Fix the overlapping
4. Remove extra vertical scrolling
5. Add this project in style_links.json

**Comment by BrownCoderAyush** [comment]
@VidhiBhatt01

**Review by VidhiBhatt01 — COMMENTED** [review]
The changes are not reflected on my device. @astha2412 @arpit456jain please verify

**Comment by arpit456jain** [comment]
hey @BrownCoderAyush  this project is already present in repo that's i can't accept this PR

but can u tell me from where u made this because that project is also looks the same

**Comment by arpit456jain** [comment]
#346

**Comment by BrownCoderAyush** [comment]
I took the help from some online source and implemented javascript on my own
I took the UI from an online source - By CodeWithHarry
It looks similar but it has more features than the online resource .
@arpit456jain

**Comment by BrownCoderAyush** [comment]
should i change the UI to some extent ?

**Comment by BrownCoderAyush** [comment]
@VidhiBhatt01 I haven't made a PR for the changes you asked for.. I have to make a PR for it .

**Review by VidhiBhatt01 — CHANGES_REQUESTED** [review]
Resolve merge conflicts

**Comment by VidhiBhatt01** [comment]
@arpit456jain are we accepting this PR?

**Comment by arpit456jain** [comment]
@BrownCoderAyush do these things
1. change its UI
2. change the songs if possible
3. try to minimise the size and remove unnecessary files

**Comment by arpit456jain** [comment]
instead of having mp3 files in this folder can't we store it on google drive or github 
like the preview images are fetching directly from github

**Comment by BrownCoderAyush** [comment]
@arpit456jain I will try to do something about songs , either I will add small size files or find a way to add some remote files .

**Review by VidhiBhatt01 — COMMENTED** [review]
Also resolve the merge conflicts

**Comment by BrownCoderAyush** [comment]
@VidhiBhatt01 should I resolve conflicts after adding required changes or earlier ? 
actually I cant figure out which thing is creating conflict

**Comment by VidhiBhatt01** [comment]
Make changes first and resolve conflicts at the end.

**Comment by VidhiBhatt01** [comment]
https://youtu.be/JtIX3HJKwfo


You can refer this

**Comment by BrownCoderAyush** [comment]
@VidhiBhatt01 hope it is ok now ,

**Pull request merged**
