### PR TITLE
Switchable Image Gallery

### PR DESCRIPTION
**Pull request by Kumar-Ankit56**
# Description

### The idea behind this project
Like we often visit e-commerce sites for shopping so in the product section there is a gallery of products which compose of 4 and 5 img as one is on the big screen and the rest of them in the mini frame, whenever we wish to look minify img at big frame we just click on small image. Project idea from there only.

### How does it work?
Here in this project, four images are available in the left minify frame, and among one image on the right side of the screen, functionality is similar to what I have stated above.

Fixes:  #533 

## Type of change

- [x] New feature (non-breaking change which adds functionality
- [x] This change requires a documentation update

# Checklist:

- [x] I have made this from my own
- [x] I have taken help from some online resources 
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented on my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK
Screenshot (121)
Screenshot (122)

### CODE REVIEW

**Comment by Kumar-Ankit56** [comment]
@VidhiBhatt01 plz review and merged

**Review by VidhiBhatt01 — CHANGES_REQUESTED** [review]
Add in style_links.json and make it responsive

**Comment by VidhiBhatt01** [comment]
https://deploy-preview-566--amazing-js-projects.netlify.app/switchable-image-gallery/#slide3

**Comment by Kumar-Ankit56** [comment]
I'm about do.

**Comment by DEEPALI-SUK** [comment]
@Kumar-Ankit56 ?

**Review by VidhiBhatt01 — COMMENTED** [review]
Reopen this when ready

**Pull request closed without merging**
