### PR TITLE
Priyanshu Puri

### LINKED ISSUE #20: priyanshu puri
## Issue Type:

[ ] Bug Report
[ ] Feature Request
[ ] Documentaion

## adding my template

- A clear and concise description of what the bug is.

## **Possible solution**

- Describe the solution you thought of.

## **Screenshots**

- If applicable, add screenshots to help explain your problem.

### PR DESCRIPTION
**Pull request by Priyanshupuri0**
# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes #20

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Explain the Testing instructions

**Test Configuration**:

- Operating system:
- Version:
- Text-editors used:

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK
image
https://priyanshupuri0.github.io/my-website/

### CODE REVIEW

**Comment by arpit456jain** [comment]
@Priyanshupuri0 is this under ces-mmmut or DCP'21 ?

**Comment by Priyanshupuri0** [comment]
Sir under ces-mmmut

**Comment by arpit456jain** [comment]
@Priyanshupuri0 buddy deadline is over now sorry but hey don't worry of template you can still submit ...but I can't give it points 

If you want to submit then please make PR on cool front end templates since this repo is for js related projects

And one more thing do not add read me when submitting

**Comment by Priyanshupuri0** [comment]
Ok sir

**Pull request closed without merging**
