### PR TITLE
Number system convertor

### PR DESCRIPTION
**Pull request by yellowberard**
# Description
In this website user can input a binary number and convert into various number system.

#355

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# Explain the Testing instructions

**Test Configuration**:

- Version: 1.0
- Text-editors used: Vs code

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK
image

### CODE REVIEW

**Review by VidhiBhatt01 — CHANGES_REQUESTED** [review]
image
Make it responsive

**Comment by yellowberard** [comment]
Made required changes.

image

**Review by VidhiBhatt01 — COMMENTED** [review]
https://deploy-preview-373--amazing-js-projects.netlify.app/number_system_convertor/numbersysystem

**Comment by VidhiBhatt01** [comment]
Still not fixed

image

**Review by astha2412 — CHANGES_REQUESTED** [review]
Fix all your elements within 2-3 days!

**Comment by yellowberard** [comment]
Made the necessary changes.

**Comment by VidhiBhatt01** [comment]
> Made the necessary changes.

Better, but if you can just increase the spacing between these buttons it will look neat.

image

**Review by VidhiBhatt01 — APPROVED** [review]

**Comment by arpit456jain** [comment]
increase the font and size of input field in small screen

**Comment by arpit456jain** [comment]
@yellowberard its still very small check again and share a video sample

**Comment by yellowberard** [comment]
https://user-images.githubusercontent.com/82977727/159072008-43a83427-1f1a-404f-8916-9d6afd95478a.mp4

Here is a demo for responsiveness

**Review by VidhiBhatt01 — CHANGES_REQUESTED** [review]
Idk why but am unable to scroll till the end

image

image

**Comment by VidhiBhatt01** [comment]
@arpit456jain are you able to scroll till the end?

**Comment by yellowberard** [comment]
You can visit this <a href="https://yellowberard.github.io/number-system-convertor/numbersysystem.html"> Link</a>

**Comment by yellowberard** [comment]
> @arpit456jain are you able to scroll till the end?

I think this is because of the netlify  preview bar overlapping the website.

Here I have attached a screenshot without the preview bar.
image

**Comment by VidhiBhatt01** [comment]
Let me just recheck

**Comment by arpit456jain** [comment]
> Let me just recheck
> 
> Edit: Still the same even without preview bar

@VidhiBhatt01 i am merging this just create a new issue for fixing it font size

**Pull request merged**
