### PR TITLE
Brick the Breaker

### LINKED ISSUE #209: Brick-Breaker
## Issue Type:

- [ ] Bug Report
- [ ] Feature Request
- [x] Documentaion

## **Describe the bug**

- A clear and concise description of what the bug is.

## **Possible solution**

- It's a cool front end game in which we break the brick

## **Screenshots**

- If applicable, add screenshots to help explain your problem.

https://user-images.githubusercontent.com/70501362/156400892-4fda26e5-025e-4748-ae28-650974063f49.mp4

### PR DESCRIPTION
**Pull request by sirilalithaadapa**
# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes #209 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Explain the Testing instructions

**Test Configuration**:

- Operating system: Windows
- Version: 11
- Text-editors used: Codepen

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented on my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK

https://user-images.githubusercontent.com/70501362/156403370-279b2bc0-ceb7-4868-ba22-7edd88f5c7c5.mp4

### CODE REVIEW

**Comment by VidhiBhatt01** [comment]
LGTM

**Comment by arpit456jain** [comment]
@astha2412 is it opening in your browser 
https://deploy-preview-211--amazing-js-projects.netlify.app/break%20the%20brick/

**Comment by astha2412** [comment]
No

**Comment by sirilalithaadapa** [comment]
even i can't see it

**Comment by sirilalithaadapa** [comment]
https://codepen.io/sirilalithaadapa/pen/JjOexgV

if needed u can check the code and output

**Comment by arpit456jain** [comment]
@sirilalithaadapa please make a new PR

**Pull request closed without merging**
