### PR TITLE
Tictactoe

### PR DESCRIPTION
**Pull request by DragonUncaged**
# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes:  #542 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

# Checklist:

- [x] I have made this from my own
- [ ] I have taken help from some online resourses 
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK
project

### CODE REVIEW

**Review by VidhiBhatt01 — CHANGES_REQUESTED** [review]
image
Ig the O and X must be in center of the box, apart from the colors I feel the previous UI was better tbh

**Comment by VidhiBhatt01** [comment]
https://deploy-preview-568--amazing-js-projects.netlify.app/tic-tac-toe%20with%202%20player/

**Comment by DragonUncaged** [comment]
Done With it.
preview

**Review by VidhiBhatt01 — CHANGES_REQUESTED** [review]
cross is fixed but circle still isn't in center

image

**Comment by DragonUncaged** [comment]
> cross is fixed but circle still isn't in center
> 
> image

Done !!

**Comment by arpit456jain** [comment]
https://github.com/angle943/tic-tac-toe

**Pull request merged**
