### PR TITLE
Added Meditation App

### PR DESCRIPTION
**Pull request by Kunal0220**
# Description

This Meditation App will help people to overcome their day to day health issues with Yoga Asanas . In todays world , people take medicine for literally every little thing . With this app I aim to provide them with a more healthy alternative for the same which would have no side effects , in turn be a long lasting solution.

Fixes:  #374 

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# Checklist:

- [x] I have made this from my own
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK
Here is the link : https://kunal0220.github.io/Meditation/

Here is a small video :

https://user-images.githubusercontent.com/71934168/162062986-2be06039-962d-4eee-a4c3-e7b55e727881.mp4

### CODE REVIEW

**Review by VidhiBhatt01 — CHANGES_REQUESTED** [review]
1. Scrolling is not smooth. Fix it if possible.
2. Make it fully responsive for all screen sizes.
image
3. Remove the extra white space from side
image
4. Add this project in style_links.json

Lastly, did you make it totally on your own?

**Comment by VidhiBhatt01** [comment]
https://deploy-preview-488--amazing-js-projects.netlify.app/meditation%20app/

**Comment by Kunal0220** [comment]
Ok I'll make all the necessary changes and make a new commit soon.

Yes I have coded the Website All by My Own except the content which is used as the cure for different problems.

**Comment by VidhiBhatt01** [comment]
@Kunal0220 any updates?

**Comment by VidhiBhatt01** [comment]
Reopen this when ready

**Pull request closed without merging**
