### PR TITLE
Added Discord Emoji Switcher

### PR DESCRIPTION
**Pull request by hariketsheth**
# Description
- Implemented a Discord-like Emoji Switcher using Javascript.

Fixes:  #707 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [x] I have made this from my own
- [ ] I have taken help from some online resourses 
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK
image
image

### CODE REVIEW

**Comment by DEEPALI-SUK** [comment]
@hariketsheth please don't open the pr until the issue has been assigned to u

**Comment by DEEPALI-SUK** [comment]
https://deploy-preview-708--amazing-js-projects.netlify.app/discord%20emoji%20switcher/

**Review by DEEPALI-SUK — CHANGES_REQUESTED** [review]
add in style_links.json of the main repo, see how others have done

also delete extra folders like custom QR code folder

**Comment by hariketsheth** [comment]
> add in style_links.json of the main repo, see how others have done
> 
> also delete extra folders like custom QR code folder

I will update the style_links.json
But the extra folder is not an error actually, It is coming because I have raised 2 PRs from the same fork. So if you merge one of them. It would only add the code once to the main repo

**Review by VidhiBhatt01 — CHANGES_REQUESTED** [review]
Can't accept this, it will raise merge conflicts in future. Always make a new PR from new branch. Close this one and make a new one

**Review by DEEPALI-SUK — APPROVED** [review]

**Comment by hariketsheth** [comment]
@arpit456jain Please merge this PR and add labels

**Comment by arpit456jain** [comment]
@hariketsheth this is looking same with this
https://www.cssscript.com/demo/discord-emoji-switcher/

**Comment by hariketsheth** [comment]
> @hariketsheth this is looking same with this https://www.cssscript.com/demo/discord-emoji-switcher/

Idea seems similar, But implemetation is different @arpit456jain 

They have used a constant array of emojis, so results are limited. Whereas I have implemented it independently using all the emojis fetched from an API. So it has better results


image



image

**Pull request merged**
