### PR TITLE
adding KeyBoard project with light and dark theme

### PR DESCRIPTION
**Pull request by Skapsime**
# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue no.)

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

# Explain the Testing instructions

**Test Configuration**:

- Operating system:
- Version:
- Text-editors used:

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK

### CODE REVIEW

**Comment by arpit456jain** [comment]
hey @Skapsime always follow these steps
1. First create a issue 
2. wait for mentor or PA to assign you that issue 
3. Then make PR and must follow the PR template specially mention the issue number you are solving like here you solved issue 47 write it like this in PR template

Fixes : #47 

And try to make separate PRs for every issue

**Comment by Skapsime** [comment]
Thank you for reply,  i will follow  all the rules in future.

**Comment by Skapsime** [comment]
Okay

**Comment by arpit456jain** [comment]
great work @Skapsime keep it up

**Comment by Skapsime** [comment]
Thank you!

**Comment by Skapsime** [comment]
Can you please  help me for finding  PR links, i can't  find this

**Comment by arpit456jain** [comment]
@Skapsime this is your PR link

https://github.com/arpit456jain/Amazing-Js-Projects/pull/53#issuecomment-886572347

The url of this PR

**Comment by Skapsime** [comment]
Got it, thanks!

**Pull request merged**
