### PR TITLE
Added piano as per #382

### PR DESCRIPTION
**Pull request by avi-pal**
This is a piano made using vanilla JS.

The piano can be played using the mouse ,
as well as by typing the keys Z S X D C V G B H N J M from the keyboard.

*SCREENSHOT*
Screenshot (64)

As per issue #382 
As per issue #384

### CODE REVIEW

**Comment by avi-pal** [comment]
I edited the describtion.

**Review by VidhiBhatt01 — CHANGES_REQUESTED** [review]
You need to make it responsive.

image


This is lovely btw, did you make it totally on your own?

**Comment by avi-pal** [comment]
Thank you
I took help from documentations of w3 schools

**Comment by avi-pal** [comment]
*SCREENSHOT*

Responsive website 
SS of the website in mobile device

Screenshot_2022-03-18-11-55-37-880_com android chrome

**Pull request merged**
