### PR TITLE
Google Search Engine Clone Added

### PR DESCRIPTION
**Pull request by gurjeetsinghvirdee**
# Description

Google Search Engine Clone using React Js and React-Router with Google API

Fixes ( #350  )

# Explain the Testing instructions

**Test Configuration**:

- Operating system: Windows
- Version: 11
- Text-editors used: VS Code

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK

Screenshot (723)

<a href="https://quizzical-payne-d3e222.netlify.app/">Preview Link</a>

### CODE REVIEW

**Review by VidhiBhatt01 — COMMENTED** [review]
https://deploy-preview-362--amazing-js-projects.netlify.app/google-search-engine-clone/public/

I can't see anything on the deployed link. It's just a blank page. Btw @gurjeetsinghvirdee are you sure you made it totally on your own?

**Comment by gurjeetsinghvirdee** [comment]
@VidhiBhatt01 for your kind info that's a react project it doesn't open like this and I didn't add a path like that to open it, first check code then say

**Comment by gurjeetsinghvirdee** [comment]
@VidhiBhatt01 that's y I add a preview link to show how it works, and code was mine i made this last year you can check my github

**Comment by VidhiBhatt01** [comment]
For your kind info we are not including react projects as of now in the repo. My job is to make sure that no plagiarized content is included and that's why I asked a simple question as your project is functioned really well. Mind your language and first check the messages in the discord channel for projects and then say and raise PRs

**Pull request closed without merging**
