### PR TITLE
Added meditation feature

### PR DESCRIPTION
**Pull request by shrey2003**
# Description

Added meditation feature
This feature allows user to meditate by selecting the required duration and required environment(forest, rain, summer night, beach) and sound effect. This project is created using HTML, CSS, JavaScript .

Fixes:  #561 

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# Checklist:

- [x] I have made this from my own
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK
Image

### CODE REVIEW

**Review by VidhiBhatt01 — CHANGES_REQUESTED** [review]
Make it responsive for all screen sizes.
image
And add the project in style_links.json

**Comment by VidhiBhatt01** [comment]
https://deploy-preview-615--amazing-js-projects.netlify.app/meditation%20feature/assets/meditation

**Comment by shrey2003** [comment]
@VidhiBhatt01 I am working on the responsiveness issue mam I will inform you if I will fail to do so

**Comment by VidhiBhatt01** [comment]
Cool. You can take 4/5 days max to fix this

**Review by DEEPALI-SUK — CHANGES_REQUESTED** [review]
for summer and rain I am not able to hear any voice

**Comment by shrey2003** [comment]
@VidhiBhatt01 Made the site responsive please check

**Review by DEEPALI-SUK — APPROVED** [review]

**Pull request merged**
