### PR TITLE
add-burger-menu

### PR DESCRIPTION
**Pull request by void-ness**
# Description

Added a new project in the vast array of informative and helpful projects built upon HTML, CSS, JS and easily available to learners. The concerned projects is a burger menu. On the web version a normal navbar is shown. However on the mobile version, the navbar collapses and the burger menu icon appears. This icon works as a toggle to open and close the menu.

Fixes:  #656 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [x] I have made this from my own
- [ ] I have taken help from some online resources 
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK
image

image

image

### CODE REVIEW

**Comment by VidhiBhatt01** [comment]
https://deploy-preview-684--amazing-js-projects.netlify.app/burger-menu/

**Comment by VidhiBhatt01** [comment]
Also, are you sure you made this on your own!? 👀

**Comment by void-ness** [comment]
> Also, are you sure you made this on your own!? 👀

Yes, I did make this on my own 😄. When I first observed the burger menu thing in other websites, I was very curious about its implementation. Instead of importing predefined classes and scripts, I decided to code my own. While coding I added a very detailed change too. Whenever someone toggles open the menu, the transition animation is ease-in. whereas when someone closes it, the transition animation is ease-out. This is a very minute detail but leaves a slightly improved user experience :)

**Comment by void-ness** [comment]
> image This looks messy, please do the needful

sure, a solution could be to display burger menu in this screen resolution too. My target screen sizes were those of desktops and those of smartphones. I did not incorporate for the screen sizes falling in between them. Will do 👍🏻 .

**Comment by void-ness** [comment]
Hey! as suggested I have worked on the change requested. Kindly see through it. Thank you. Looking forward to contributing more in the future. Attaching a ss for reference.

image

**Review by DEEPALI-SUK — CHANGES_REQUESTED** [review]
image

in mobile view it is not working properly

**Comment by void-ness** [comment]
Good suggestion. I made the changes. Kindly check. attaching a ss for reference.
image

In the image above the screen resolution is a bit bigger than an average phone screen size but will work accordingly for normal phones too.

**Review by VidhiBhatt01 — CHANGES_REQUESTED** [review]
Still the same in all resolutions.
image

**Comment by void-ness** [comment]
@VidhiBhatt01 can you check once again if the deployment link/ The link you referred to for reviewing is updated? I have fetched the latest code from the repository and the website works smoothly on my system. re attaching a current screen grab which confirms the issue being resolved.

image


image


image

**Comment by DEEPALI-SUK** [comment]
@arpit456jain we are not able to see the updated changes

**Comment by void-ness** [comment]
Thank you for the assistance. In the link below the updated code is accessible. I would be very thankful if you can spare some time and review the changes and if everything seems fine approve my submission.

https://deploy-preview-684--amazing-js-projects.netlify.app/burger-menu/#

**Review by VidhiBhatt01 — APPROVED** [review]

**Comment by void-ness** [comment]
Hey! 
Thank you so very much for clearing my request to be merged. I am a GSSoC contributor. I will be very grateful if you can generously score my PR. Since it being the Last week, some of my PRs have not been considered for merging. Due to that I am currently short of 35 points to reach my next milestone. It would very helpful if you can help me with that. 

Keeping that aside, I enjoyed a lot while contributing to this amazing repository. Got to know about so many more exciting projects and some good coding practices. Thank you for the opportunity.

**Comment by VidhiBhatt01** [comment]
Am glad you liked our repo. PA will merge the PR and do the needful, dw :)

**Pull request merged**
