### PR TITLE
Double Vertical Slider

### PR DESCRIPTION
**Pull request by Atif0604**
# Description

Added Double Vertical Slider
Fixes: #88

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# Explain the Testing instructions

**Test Configuration**:

- Operating system:
- Version:
- Text-editors used:

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK

### CODE REVIEW

**Comment by Atif0604** [comment]
Hey @arpit456jain 
Please Review

**Comment by arpit456jain** [comment]
@Atif0604 always right like 

Fixes: #88

**Comment by arpit456jain** [comment]
@Atif0604 i think it should be a cycle when we click 4 times on up or down

**Comment by Atif0604** [comment]
> @Atif0604 i think it should be a cycle when we click 4 times on up or down

its a cycle only @arpit456jain

**Comment by Atif0604** [comment]
> @Atif0604 always right like
> 
> Fixes: #88

ohk @arpit456jain

**Review by ankitapuri — APPROVED** [review]

**Comment by ankitapuri** [comment]
Its great @Atif0604 

U can check it once @arpit456jain  and merge it

**Pull request merged**
