### PR TITLE
added a sound board

### PR DESCRIPTION
**Pull request by kheya19**
# Description

I have made this using HTML, CSS, and JS. On clicking the buttons the above sounds is played.

Fixes:  #419

# Checklist:

- [ x] I have made this from my own
- [x ] I have taken help from some online resourses 
- [x ] My code follows the style guidelines of this project
- [x ] I have performed a self-review of my own code

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK
screenshot--2022 03 24-21_14_08

### CODE REVIEW

**Review by astha2412 — COMMENTED** [review]
https://deploy-preview-426--amazing-js-projects.netlify.app/sound%20board/

**Comment by astha2412** [comment]
@kheya19 Fill description properly....Rest is good!

**Comment by kheya19** [comment]
> @kheya19 Fill description properly....Rest is good! 

Can you please mention which part should I change

**Review by VidhiBhatt01 — APPROVED** [review]

**Comment by VidhiBhatt01** [comment]
@astha2412 ig the description is proper. Am I missing out on something? Can you elaborate on what changes do you want?

**Review by VidhiBhatt01 — COMMENTED** [review]
@kheya19 just add this project in style_links.json

**Comment by kheya19** [comment]
> @kheya19 just add this project in style_links.json

Ok

**Comment by arpit456jain** [comment]
@kheya19 
https://codepen.io/laraibmalik/pen/eYvbVBy

@mentors have a look and check whether its 95-100% plagrised  or not if its under plag let me know
@astha2412 @VidhiBhatt01 @DEEPALI-SUK @DEEPIKA-SUK

**Comment by arpit456jain** [comment]
@astha2412 check others PRs by @kheya19 in all three repos for plag

**Pull request closed without merging**
