### PR TITLE
Custom Range Slider

### PR DESCRIPTION
**Pull request by Atif0604**
# Description
Added Custom Range Slider

Fixes # (issue no.)
Custom Range Slider #66

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# Explain the Testing instructions

**Test Configuration**:

- Operating system:
- Version:
- Text-editors used:

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK

### CODE REVIEW

**Comment by Atif0604** [comment]
Hey @ankitapuri @arpit456jain  
Please Review my PR

**Comment by arpit456jain** [comment]
hey @Atif0604 its really awesome can you do one thing .
Add the value inside the circle where it is

**Comment by Atif0604** [comment]
> hey @Atif0604 its really awesome can you do one thing .
> Add the value inside the circle where it is

ok just give me a sec
i will do it

**Comment by Atif0604** [comment]
Hey @arpit456jain 
now you can check the value is also inside the circle after dropping

**Comment by ankitapuri** [comment]
@Atif0604 its looking perfect now , can u make it responsive if possible or would you like to do in another PR

**Comment by Atif0604** [comment]
> @Atif0604 its looking perfect now , can u make it responsive if possible or would you like to do in another PR

@ankitapuri will do it in another PR

**Comment by ankitapuri** [comment]
> > @Atif0604 its looking perfect now , can u make it responsive if possible or would you like to do in another PR
> 
> @ankitapuri will do it in another PR

okay!

**Comment by arpit456jain** [comment]
Ok @Atif0604 i am merging this PR
But do one thing delete the forked and fork it again and always make PR from a different branch not From master

**Comment by Atif0604** [comment]
> Ok @Atif0604 i am merging this PR
> But do one thing delete the forked and fork it again and always make PR from a different branch not From master

Sure @arpit456jain will do this

**Pull request merged**
