### PR TITLE
Password-generator project added

### PR DESCRIPTION
**Pull request by Aayush987**
# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes:  #613

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [x] I have made this from my own
- [ ] I have taken help from some online resourses 
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK

https://user-images.githubusercontent.com/92387745/167299847-cd4088a5-baa9-4eca-9383-53211d9f7b6e.mp4

### CODE REVIEW

**Review by DEEPALI-SUK — CHANGES_REQUESTED** [review]
1. add in style_links.json of the main repo
2. in mobile view fonts are not visible properly

**Comment by DEEPALI-SUK** [comment]
> > @Aayush987 make it responsive for small screens
> 
> Can i submit it tomorrow? Actually i am out of town right now.

yeah sure

**Comment by arpit456jain** [comment]
> > @Aayush987 make it responsive for small screens
> 
> @arpit456jain Actually, I am not quite getting how to make it responsive for small screens because I am still learning web dev, but I think it is looking quite good on mobile screens right now, phone But if you could help me with it, it will be really helpful for me.Otherwise, I think it is looking good on small screens.

Write media queries 
https://www.w3schools.com/css/css3_mediaqueries.asp
u can write different css for small screens

**Comment by Aayush987** [comment]
> > > @Aayush987 make it responsive for small screens
> > 
> > @arpit456jain Actually, I am not quite getting how to make it responsive for small screens because I am still learning web dev, but I think it is looking quite good on mobile screens right now, phone But if you could help me with it, it will be really helpful for me.Otherwise, I think it is looking good on small screens.
> 
> Write media queries 
> https://www.w3schools.com/css/css3_mediaqueries.asp
> u can write different css for small screens
> 

Oh, ok thank you so much . I will improvise it.

**Review by DEEPALI-SUK — CHANGES_REQUESTED** [review]
Still the fonts in the green boxes are not visible in mobile view, just increase the font size

**Comment by Aayush987** [comment]
> Still the fonts in the green boxes are not visible in mobile view, just increase the font size

Ok .I will do it by evening.

**Comment by Aayush987** [comment]
> Still the fonts in the green boxes are not visible in mobile view, just increase the font size

DONE.

**Review by DEEPALI-SUK — APPROVED** [review]

**Pull request merged**
