### PR TITLE
Added Connect Four Game 

### LINKED ISSUE #37: Connect 4 Game
## Issue Type:

- [ ] Bug Report
- [x] Feature Request
- [ ] Documentaion

## **Possible solution**

- Connect Four is a 6 * 7 grid-based two-player game. If a player matches any four cells consecutively (in a row, column, or diagonal), the player wins.

### PR DESCRIPTION
**Pull request by kiruba-r11**
# Description

Connect Four is a 6 * 7 grid-based two-player game. In this game, the player wins if he/she fills any four consecutive rows, columns, or diagonal cells.

Fixes #37 

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK
Screenshot 2021-07-17 at 2 14 13 PM
Screenshot 2021-07-17 at 2 14 23 PM

### CODE REVIEW

**Comment by ankitapuri** [comment]
@kiruba-r11 please also send a video or gif

**Comment by kiruba-r11** [comment]
https://user-images.githubusercontent.com/76843281/126035348-7bbc39d9-ef71-42ee-a8ee-03fa59b3a24f.mov

**Comment by ankitapuri** [comment]
Great work @kiruba-r11

**Review by ankitapuri — APPROVED** [review]

**Comment by ankitapuri** [comment]
@arpit456jain u can merge it

**Comment by kiruba-r11** [comment]
@ankitapuri Thanks a lot!. This really motivates me.

**Pull request merged**
