### PR TITLE
resume builder added #576

### PR DESCRIPTION
**Pull request by priyanshi1282**
# Description

Helps to create your resume and gets you print it.

Fixes:  #576 

## Added a new js project.

- [x] New feature (non-breaking change which adds functionality)

# Checklist:

- [x] I have made this from my own
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK
preview
input
preview
print-preview
responsive1
responsive2

### please consider this under GSSoC'22 contribution.

### CODE REVIEW

**Review by VidhiBhatt01 — APPROVED** [review]
Did you totally make this on your own? If not add the resources you used in a readme file. Also, if you have raised this issue in any other repo then please close this PR

**Comment by priyanshi1282** [comment]
> Did you totally make this on your own? If not add the resources you used in a readme file. Also, if you have raised this issue in any other repo then please close this PR

I did took js logic reference from a video and understood it, rest all is coded by me.

**Comment by VidhiBhatt01** [comment]
> > Did you totally make this on your own? If not add the resources you used in a readme file. Also, if you have raised this issue in any other repo then please close this PR
> 
> I did took js logic reference from a video and understood it, rest all is coded by me.

Add the video link in the readme file

**Comment by priyanshi1282** [comment]
> > > Did you totally make this on your own? If not add the resources you used in a readme file. Also, if you have raised this issue in any other repo then please close this PR
> > 
> > 
> > I did took js logic reference from a video and understood it, rest all is coded by me.
> 
> Add the video link in the readme file

Added 👍 Please check once.

**Pull request merged**
