### PR TITLE
Added Live user filter

### PR DESCRIPTION
**Pull request by Avik-creator**
## Feature Added:

- I have worked on issue #391 
- I have done it by using the tutorial of Traversy Media
- Link to that video is : https://youtu.be/JkeyKeK3V24

### CODE REVIEW

**Comment by Avik-creator** [comment]
@arpit456jain it gives random users so I can't control the users location. If I have to add Indian location then they will not change with refreshing the site.

**Comment by Avik-creator** [comment]
Regarding the color scheme I will change it and make more natural

**Comment by VidhiBhatt01** [comment]
@Avik-creator what's the update here?

**Review by VidhiBhatt01 — COMMENTED** [review]
Also, add your project in style_links.json

**Comment by Avik-creator** [comment]
I will work on it tomorrow as my clg assignment is going on. I update it as soon as I am done

**Review by Avik-creator — COMMENTED** [review]
# Worked On Issue Number: #391 
# Made Some Necessary Changes as Requested.
# Added Readme File.
# Updated style_links.json file as Requested.

**Comment by Avik-creator** [comment]
@VidhiBhatt01 Please check the changes and suggest if there is more to improve.

**Review by VidhiBhatt01 — CHANGES_REQUESTED** [review]
Almost perfect, can you just add some spacing between the user image and name? Will barely take 2mins.

image

https://deploy-preview-412--amazing-js-projects.netlify.app/live%20user%20filter/

**Comment by Avik-creator** [comment]
I will do it tonight as my i am watching IPL. Lol

**Comment by Avik-creator** [comment]
@VidhiBhatt01 Can you please check it now as I have done that was requested.

**Review by VidhiBhatt01 — CHANGES_REQUESTED** [review]
Few names are still like this

image

Also, the spacing must be uniform

image

**Comment by Avik-creator** [comment]
@VidhiBhatt01 it gives random names and location. I can't change it since it is based on random user.

**Comment by Avik-creator** [comment]
@VidhiBhatt01 I will see regarding address what can I do.

**Review by Avik-creator — COMMENTED** [review]
Done with the changes

**Comment by Avik-creator** [comment]
Screenshot 2022-03-27 at 3 51 15 PM
Here is the result after the changes.
@VidhiBhatt01

**Review by arpit456jain — APPROVED** [review]

**Pull request merged**
