### PR TITLE
project_added

### PR DESCRIPTION
**Pull request by priyanshu688**
# Description

I have added the Falling Ball Game project which is built using the JavaScript Language.

Fixes:  #432

## Type of change

- [x] This change requires a documentation update

# Checklist:

- [x] I have made this from my own
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK
https://priyanshu688.github.io/Falling_Ball_Game/

### CODE REVIEW

**Comment by priyanshu688** [comment]
@arpit456jain Kindly review and merge this.

**Review by DEEPALI-SUK — COMMENTED** [review]
@priyanshu688 u have copied code from here 
https://youtu.be/lvzzdwBorG4

**Review by VidhiBhatt01 — COMMENTED** [review]
@priyanshu688 do you want to clarify anything?

**Comment by arpit456jain** [comment]
> @priyanshu688 do you want to clarify anything?

**Pull request closed without merging**
