### PR TITLE
Added function grapher files

### PR DESCRIPTION
**Pull request by XZANATOL**
# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes:  #405 

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# Checklist:

- [x] I have made this from my own
- [x] I have taken help from some online resourses 
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK

https://htmlpreview.github.io/?https://github.com/XZANATOL/Amazing-Js-Projects/blob/Function_Grapher/Function_Grapher/index.html

### CODE REVIEW

**Review by VidhiBhatt01 — CHANGES_REQUESTED** [review]
Same problem as the previous PR. The sizing does not look good on small screens.

image


Can you add some margin or padding here?
image

Lastly, are you referring to something for all such projects or are you making it totally on your own?

**Comment by XZANATOL** [comment]
@VidhiBhatt01 Requested changes applied, and no I'm not referring to another source considering the page style, It's just a basic template I made to save time when I begin in another project instead of building the page from scratch.

image

Finally, I'm going to DM you on Discord right now if you're online. If not we can coordinate another time to voice.

**Comment by XZANATOL** [comment]
@VidhiBhatt01 Done.

**Review by VidhiBhatt01 — APPROVED** [review]
https://deploy-preview-431--amazing-js-projects.netlify.app/function_grapher/

**Review by arpit456jain — APPROVED** [review]

**Pull request merged**
