### PR TITLE
Mousemove glitter effect by js

### PR DESCRIPTION
**Pull request by mayank-del**
# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes:  #546 

## Type of change

It uses beautiful vanilla javascript codes to make small colorful circles to follow the movement of mouse

- [x ] New feature (non-breaking change which adds functionality)
- [x ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

# Checklist:

- [ x] I have made this from my own
- [ x] I have taken help from some online resourses 
- [x ] My code follows the style guidelines of this project
- [x ] I have performed a self-review of my own code

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK

### CODE REVIEW

**Comment by VidhiBhatt01** [comment]
https://deploy-preview-549--amazing-js-projects.netlify.app/mousemove%20effect/i

**Review by VidhiBhatt01 — CHANGES_REQUESTED** [review]
Remove extra files from the PR

**Comment by mayank-del** [comment]
@VidhiBhatt01  maam deleted the extra files

**Review by VidhiBhatt01 — CHANGES_REQUESTED** [review]
Just resolve merge conflicts and we are good to go!

**Comment by mayank-del** [comment]
maam actually I made upgradation in your background  color changer  project 1 month back  but in different  branch and that was already merged into master  but now in this branch also same 1 month older change is reflecting and if i delete those changes it is saying that i am conflicting with master branch.  but i trust me, i haven't even touched those files. what we should do now?

**Review by VidhiBhatt01 — APPROVED** [review]
Fixed it

**Comment by VidhiBhatt01** [comment]
I am also unable to fix the merge conflicts. Just delete this branch, close this PR and make a new one

**Pull request closed without merging**
