### PR TITLE
Weather App

### PR DESCRIPTION
**Pull request by Atif0604**
# Description
Added Weather App

Fixes # (issue no.)

Weather App #14

## Type of change

- [ ✔️] New feature (non-breaking change which adds functionality)

# Explain the Testing instructions

**Test Configuration**:

- Operating system: Windows 
- Version: 10
- Text-editors used: VS Code

# Checklist:

- [ ✔️] My code follows the style guidelines of this project
- [ ✔️] I have performed a self-review of my own code
- [✔️ ] I have commented my code, particularly in hard-to-understand areas
- [✔️ ] I have made corresponding changes to the documentation
- [✔️ ] My changes generate no new warnings
- [✔️ ] I have added tests that prove my fix is effective or that my feature works
- [✔️ ] New and existing unit tests pass locally with my changes
- [ ✔️] Any dependent changes have been merged and published in downstream modules

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK
Weather-App

### CODE REVIEW

**Comment by arpit456jain** [comment]
@ankitapuri please review

**Comment by ankitapuri** [comment]
@arpit456jain u can merge it

**Comment by Atif0604** [comment]
> @arpit456jain u can merge it

Hey @ankitapuri is there is any possibility to increase the level as i have also used 2 api with it(unsplash api and openweather api) for the project

**Comment by ankitapuri** [comment]
> > @arpit456jain u can merge it
> 
> Hey @ankitapuri is there is any possibility to increase the level as i have also used 2 api (unsplash api and openweather api) for the project
> unsplash api for dynamic backgrounds
> openweather api for weather forecast of differenet places

Okay sure . I will change it

**Comment by arpit456jain** [comment]
Great work @Atif0604

**Pull request merged**
