### PR TITLE
Leap year modification

### PR DESCRIPTION
**Pull request by mayank-del**
# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes:  #572 

## Type of change

I added awesome css effects to make it mush better than older one

- [ x] New feature (non-breaking change which adds functionality)

# Checklist:

- [ x] I have made this from my own
- [x ] My code follows the style guidelines of this project
- [ x] I have performed a self-review of my own code
- [ x] My changes generate no new warnings

Screenshot 2022-05-01 073903

### CODE REVIEW

**Review by VidhiBhatt01 — CHANGES_REQUESTED** [review]
1. Increase the sizing and make it properly responsive.
image
2. Add this in style_links.json

**Comment by VidhiBhatt01** [comment]
https://deploy-preview-582--amazing-js-projects.netlify.app/leap%20year/

**Comment by VidhiBhatt01** [comment]
It is still not fixed even though you made commits...

**Comment by mayank-del** [comment]
@VidhiBhatt01  maam , In my computer , it is showing responsive for every phone , Can you please elaborate, the issue , i am not not getting it, please tell me , what's the problem

**Comment by mayank-del** [comment]
Screenshot 2022-05-04 152933


you can see @VidhiBhatt01  maam , it is responsive for <290px

**Pull request merged**
