### PR TITLE
Added Instagrammini

### PR DESCRIPTION
**Pull request by SamarthKadam**
# Description

Fixes:  #436 

## Type of change

- [x ] New feature (non-breaking change which adds functionality)

# Checklist:

- [x] I have made this from my own 
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK
Please read the Readme before opening
https://instagrampc.netlify.app/

### CODE REVIEW

**Review by VidhiBhatt01 — CHANGES_REQUESTED** [review]
https://deploy-preview-478--amazing-js-projects.netlify.app/instagrammini/

1. Make it responsive for all screen sizes.
image

2. Reduce the number of files changed. No need to add much functionality.

3. Add this project in style_links.json

Also, did you make it totally on your own? 👀

**Comment by SamarthKadam** [comment]
Ohk

**Comment by SamarthKadam** [comment]
Why there is a difference between https://deploy-preview-478--amazing-js-projects.netlify.app/instagrammini/ and instagrampc.netlify.app

**Comment by SamarthKadam** [comment]
Please Reply? What's the reason for above error

**Comment by arpit456jain** [comment]
> Please Reply? What's the reason for above error

its deploying ur this PR

**Comment by SamarthKadam** [comment]
> @SamarthKadam 
> screencapture-deploy-preview-478-amazing-js-projects-netlify-app-instagrammini-2022-04-07-00_05_07
> 
> not loading 
> 
> and its asking to on camera first i think its of no use 
> @VidhiBhatt01 @astha2412 @DEEPALI-SUK @DEEPIKA-SUK ur views

Hello sirs the files are not loaded properly so their not getting rendered


Sir try this in your pc instagrampc.netlify.app

**Comment by arpit456jain** [comment]
@SamarthKadam its also blank

**Comment by arpit456jain** [comment]
wait

**Comment by arpit456jain** [comment]
yes its fine on ur url but not deployed in this PR

**Comment by SamarthKadam** [comment]
In the above link instagrampc.netlify.app it works.

**Comment by SamarthKadam** [comment]
So  what to do next?

**Comment by arpit456jain** [comment]
@SamarthKadam optimise it on ur master branch and then make a new PR

**Comment by SamarthKadam** [comment]
Optimize in terms of what? And should I add project in style_links.json?

**Comment by arpit456jain** [comment]
> Optimize in terms of what? And should I add project in style_links.json?

i mean remove un wanted files and decrease its overall size

**Pull request closed without merging**
