### PR TITLE
Image Filter App

### PR DESCRIPTION
**Pull request by Atif0604**
# Description

Added Image Filter App

Fixes # (issue no.)

Image Filter App #74

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# Explain the Testing instructions

**Test Configuration**:

- Operating system:
- Version:
- Text-editors used:

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK

### CODE REVIEW

**Comment by Atif0604** [comment]
Hey @arpit456jain 
please Review my PR

**Comment by arpit456jain** [comment]
hey @Atif0604  your PR contains change in snake game please remove that changes

**Comment by arpit456jain** [comment]
@Atif0604 rebase your branch

**Comment by Atif0604** [comment]
> hey @Atif0604 your PR contains change in snake game please remove that changes

I don't know how this happens 
this issue is same every time i make a PR😔

**Comment by Atif0604** [comment]
> @Atif0604 rebase your branch

i rebased my branch by checking out to master branch but the snake commit is still there😔
@arpit456jain

**Comment by arpit456jain** [comment]
@Atif0604 you have to pull changes in your branch by
git pull origin master
and then push it to github by 
git push orign branchname

**Comment by Atif0604** [comment]
> @Atif0604 you have to pull changes in your branch by
> git pull origin master
> and then push it to github by
> git push orign branchname

It says Everything is up to date

**Comment by Atif0604** [comment]
i guess again i have to delete the repo the fork it then make further PR
i don't know how is this happening it never happened before
if for this time if you can merge then after that every time i have delete the whole and then make the PR
@arpit456jain

**Comment by arpit456jain** [comment]
@Atif0604 hey come on meet tomorrow

**Comment by Atif0604** [comment]
> @Atif0604 hey come on meet tomorrow around 2 pm
> Send me the link on slack

Sure @arpit456jain

**Comment by arpit456jain** [comment]
Do not delete the repo @Atif0604

**Comment by Atif0604** [comment]
> Do not delete the repo @Atif0604

Sure Sure @arpit456jain

**Pull request merged**
