### PR TITLE
Rocket launcher web animation

### LINKED ISSUE #79: Rocket Web Animation
## Issue Type:

- [ ] Bug Report
- [ ] Feature Request
- [ ] Documentaion

## **Describe the bug**

- A clear and concise description of what the bug is.

## **Possible solution**

- Describe the solution you thought of.

## **Screenshots**

- If applicable, add screenshots to help explain your problem.

### PR DESCRIPTION
**Pull request by Skapsime**
# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes #79 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

# Explain the Testing instructions

**Test Configuration**:

- Operating system:
- Version:
- Text-editors used:

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK

### CODE REVIEW

**Comment by arpit456jain** [comment]
@ankitapuri i think this will comes under css effects 
your views please

**Comment by ankitapuri** [comment]
> @ankitapuri i think this will comes under css effects
> your views please

yes it would come under css effects

**Comment by arpit456jain** [comment]
@Skapsime can you make PR on  to css effects repo for this project  ??
just create a issue and make PR don't wait for assignment this time

**Comment by Skapsime** [comment]
> > @ankitapuri i think this will comes under css effects
> > your views please
> 
> yes it would come under css effects

i think it would come under js because most of the part i used js.

**Comment by arpit456jain** [comment]
@Skapsime yup you used js i know but its kind of special effects project not a JS project 
if you want i can do one thing , I can merge this PR and you can add this same project in css effects also 
lvl 2 for both

**Comment by Skapsime** [comment]
> @Skapsime yup you used js i know but its kind of special effects project not a JS project
> if you want i can do one thing , I can merge this PR and you can add this same project in css effects also
> lvl 2 for both

 okay and thank you 😊

**Comment by Skapsime** [comment]
thanks you so much

**Comment by Skapsime** [comment]
I have created an issue in AMAZING CSS EFFECTS repo please assign me

**Pull request merged**
