### PR TITLE
Added the preview images & updated style.js

### PR DESCRIPTION
**Pull request by prabhkaur301**
# Description

I added preview images of the projects which did not have. Also I made a minor change in style,js , so that the space between project names can be omitted . (Due to space in project names , some project links are not working)

Fixes:     #395 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [x] I have made this from my own
- [ ] I have taken help from some online resources 
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK

https://user-images.githubusercontent.com/57444962/159553725-2794e51f-1956-4be1-9531-2c46973fb029.mp4

### CODE REVIEW

**Review by VidhiBhatt01 — CHANGES_REQUESTED** [review]
LGTM but still few images are missing.
1. image

2. image

3. image

4. image

**Comment by prabhkaur301** [comment]
> LGTM but still few images are missing.
> 
> 1. image
> 2. image
> 3. image
> 4. image


Actually mam, these are the reasons why I not added the preview picture of these projects :- 

1. That dice game updated is duplicate of previous dice game . 
2. That calculator project has further folders of different types of calculators , there is no direct link
image

3. That pig game is reloading continuously, I'm unable to take screenshot of that.

**Comment by prabhkaur301** [comment]
Actually mam, these are the reasons why I not added the preview picture of these projects :- 

1. That dice game updated is duplicate of previous dice game . 
2. That calculator project has further folders of different types of calculators , there is no direct link
image

3. That pig game is reloading continuously, I'm unable to take screenshot of that.

**Comment by prabhkaur301** [comment]
> Also, we have a PR related to the design and major UI changes of the website. So I would suggest that you wait for 24/30 hours. Till then it will be merged most probably. Once it is merged, you can pull the changes and then update your branch with the changes I suggested.

Sure mam :)

**Comment by prabhkaur301** [comment]
Actually mam, these are the reasons why I not added the preview picture of these projects :- 

1. That dice game updated is duplicate of previous dice game . 
2. That calculator project has further folders of different types of calculators , there is no direct link
image

3. That pig game is reloading continuously, I'm unable to take screenshot of that.

**Comment by prabhkaur301** [comment]
@VidhiBhatt01  should I delete those projects which are duplicate and not working properly?

**Comment by arpit456jain** [comment]
> @VidhiBhatt01 should I delete those projects which are duplicate and not working properly?

not now @prabhkaur301

**Comment by arpit456jain** [comment]
@prabhkaur301 i am merging ur PR hope all image will render properly

**Pull request merged**
