### PR TITLE
Sneaker Site files added

### LINKED ISSUE #227: Add a Sneaker Site
## Issue Type:

- [x] Feature Request

## **Describe the bug**
- I wish to add a responsive Sneaker site which will give a good practice of both CSS and JS to begineers.

## **Screenshots**
Nike1

Nike2

Nike3

Nike5

Nike4

### PR DESCRIPTION
**Pull request by Adit0507**
# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes #227 

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# Explain the Testing instructions

**Test Configuration**:

- Operating system: Windows 10
- Version: Latest
- Text-editors used: Visual Studio Code

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] New and existing unit tests pass locally with my changes

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK

### CODE REVIEW

**Comment by Adit0507** [comment]
This is my new PR for the sneaker site, I hope it's working well now

**Comment by arpit456jain** [comment]
@Adit0507 yes its working but is it a Js project ?

**Comment by Adit0507** [comment]
> @Adit0507 yes its working but is it a Js project ?

Yes it is. This project will give a good practice for JS as well as CSS to beginners and it is fully responsive.

**Comment by VidhiBhatt01** [comment]
I loved the site! Did you make it on your own @Adit0507 or did you refer any tutorial?

**Comment by VidhiBhatt01** [comment]
> > I loved the site! Did you make it on your own @Adit0507 or did you refer any tutorial?
> 
> I referred to a tutorial for this website. If everything is working well now, can u please merge it.

Great! The site looks good to me. @arpit456jain will look into this and merge it soon

**Pull request merged**
