### PR TITLE
Scrollbar

### PR DESCRIPTION
**Pull request by soumali28**
# Description

I have created a custom scrollbar for the website

Fixes # (issue no.)

#248 

## Type of change

This is added to inhance the user experience.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK

Amazing-JS-Projects - Google Chrome 3_4_2022 5_41_25 PM

### CODE REVIEW

**Comment by arpit456jain** [comment]
@soumali28

**Comment by soumali28** [comment]
What changes  shall I make @arpit456jain ?

**Comment by arpit456jain** [comment]
@soumali28 resolve the conflicts

**Comment by soumali28** [comment]
I have created another pr  #307 u can check this and close this pr.

**Pull request closed without merging**
