### PR TITLE
Readme updated

### PR DESCRIPTION
**Pull request by gurjeetsinghvirdee**
# Description

Update all the open-source program images

Fixes  ( #360  )

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

# Explain the Testing instructions

**Test Configuration**:

- Operating system: Windows
- Version: 11
- Text-editors used: VS Code

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK

Screenshot (724)

### CODE REVIEW

**Review by VidhiBhatt01 — CHANGES_REQUESTED** [review]
I want all 3 aligned vertically in the same line with the same size and equal spacing between them. If you are facing problem in sizing the GSSoC 22 image you can change it and add a suitable from the internet.

**Comment by gurjeetsinghvirdee** [comment]
Are you sure, it looks much better in this way,  you want 3 img in vertical line seriously , it will look worse

**Comment by gurjeetsinghvirdee** [comment]
@VidhiBhatt01 
Screenshot (727)
 If I increase more height , third image will be goes in next line

**Comment by VidhiBhatt01** [comment]
> @VidhiBhatt01 Screenshot (727) If I increase more height , third image will be goes in next line

Ahh okay, just keep the GSSOC Image first. 

Btw can we do something like this?
image
One image per line, sirf dev incept vali image ko badi kar do

**Comment by gurjeetsinghvirdee** [comment]
> > @VidhiBhatt01 Screenshot (727) If I increase more height , third image will be goes in next line
> 
> Ahh okay, just keep the GSSOC Image first.
> 
> Btw can we do something like this? image One image per line, sirf dev incept vali image ko badi kar do

ye ky baat hui 😤krta hu fix and can you check your dm

**Comment by gurjeetsinghvirdee** [comment]
@VidhiBhatt01 
Screenshot (728)
Screenshot (729)

**Review by VidhiBhatt01 — APPROVED** [review]
Sorry for the delay in reviewing

**Review by astha2412 — APPROVED** [review]

**Pull request merged**
