### PR TITLE
Added Guess The Number game

### LINKED ISSUE #221: Guess the number game
I am a contributor from GSSoc 2022. I want to add guess the number game, which will also tell the previous attempts and previous number of guesses.

### PR DESCRIPTION
**Pull request by Ravnoor12**
# Description

I have created a Guess the Number Game. In this game one need to guess the number, after a guess player will get to know whether the guess was correct or higher than correct or lower than the correct and along with that player's previous guesses will also get displayed. There are 2 difficulty levels, easy in which player has 10 chances and hard level in which player has 5 chances.

Fixes #221 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

# Explain the Testing instructions

**Test Configuration**:

- Operating system : Window
- Version : 11
- Text-editors used: Vs Code

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] Any dependent changes have been merged and published in downstream modules
# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK
Screenshot 1
Screenshot 2
Screenshot 3

### CODE REVIEW

**Comment by Ravnoor12** [comment]
I am contributor at GSSoC - 2022. Kindly review it and merge it.

**Comment by VidhiBhatt01** [comment]
It's fun to play this game!!

**Review by VidhiBhatt01 — APPROVED** [review]

**Comment by VidhiBhatt01** [comment]
Did you make it totally on your own from scratch?

**Comment by Ravnoor12** [comment]
> Did you make it totally on your own from scratch?

Not Totally, I took a little help from yt :).

**Pull request merged**
