### PR TITLE
#368 - Alarm Clock

### PR DESCRIPTION
**Pull request by pushpanjali-10**
An alarm clock made with features such as snooze and selection of music

Fixes:  #368

image

### CODE REVIEW

**Review by DEEPALI-SUK — COMMENTED** [review]
@pushpanjali-10 in mobile view letters are not properly visible, increase the font size

**Comment by pushpanjali-10** [comment]
> @pushpanjali-10 in mobile view letters are not properly visible, increase the font size

okay, will do

**Review by VidhiBhatt01 — APPROVED** [review]
https://deploy-preview-441--amazing-js-projects.netlify.app/alarm_clock/

**Comment by VidhiBhatt01** [comment]
Just a suggestion, always keep HTML and CSS in different files. Do keep this in mind when you make projects in future :)

**Comment by pushpanjali-10** [comment]
> Just a suggestion, always keep HTML and CSS in different files. Do keep this in mind when you make projects in future :)

sure sir

**Pull request merged**
