### PR TITLE
Hangman Game

### PR DESCRIPTION
**Pull request by AnIkeT126**
# Description

The hangman game is about guessing a random word by guessing letters one by one. If the player runs out of guesses, the game is over.
The solution:
Set a maximum limit for guesses.
Display the remaining number of guesses to the player.
Provide the player with an interface to input their guesses.

Fixes: #496 

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# Checklist:

- [x] I have taken help from some online resourses 
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK

image

### CODE REVIEW

**Comment by AnIkeT126** [comment]
@arpit456jain and @VidhiBhatt01 please review the changes owing to issue #496 and previous PR #497

**Review by VidhiBhatt01 — CHANGES_REQUESTED** [review]
https://deploy-preview-501--amazing-js-projects.netlify.app/hangman%20game/

Awesome! Just make this 2 changes and then we are good to go.
1. Add this game in style_links.json
2. Add a readme file wherein you add a screenshot of the game and explain in brief about it. Do mention that play the game from Desktop/Tablet for better experience.

**Comment by VidhiBhatt01** [comment]
And please make changes in this PR only. Don't create a new PR.

**Comment by AnIkeT126** [comment]
@VidhiBhatt01 a readme with a screenshot as you mentioned is already there.
I will just add it in the style.links.json

**Comment by AnIkeT126** [comment]
@VidhiBhatt01 and @arpit456jain I  have made all the necessary changes to the best of my knowledge. Please merge it upon finding it correct and if possible tell me the level label this will be evaluated on.

**Pull request merged**
