### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by aachal28**
# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes:  #669

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [x] I have made this from my own
- [ ] I have taken help from some online resourses 
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK

### CODE REVIEW

**Comment by aachal28** [comment]
i have added js project

**Review by VidhiBhatt01 — APPROVED** [review]
It wasn't supposed to be fixed like this but okay

**Comment by arpit456jain** [comment]
u had deleted the main HTML file 😥

**Review by VidhiBhatt01 — CHANGES_REQUESTED** [review]
resolve merge conflicts




you can refer this
https://www.youtube.com/watch?v=JtIX3HJKwfo

**Review by VidhiBhatt01 — CHANGES_REQUESTED** [review]
@aachal28

**Comment by aachal28** [comment]
> resolve merge conflicts
> 
> you can refer this https://www.youtube.com/watch?v=JtIX3HJKwfo

Resolved  done 
please check i have done right or wrong?

**Comment by arpit456jain** [comment]
@aachal28 u have to add ur project in a new folder u r replacing the index file of root folder which is wrong
make a new folder and put all of ur files there and make a new Pr

**Pull request closed without merging**
