### PR TITLE
Colorpicker

### PR DESCRIPTION
**Pull request by DragonUncaged**
# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes:  #621 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

# Checklist:

- [x] I have made this from my own
- [ ] I have taken help from some online resourses 
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK

### CODE REVIEW

**Review by astha2412 — COMMENTED** [review]
https://deploy-preview-631--amazing-js-projects.netlify.app/color%20picker/

**Comment by astha2412** [comment]
@DragonUncaged Add preview.png

**Comment by astha2412** [comment]
[](url
Screenshot (438)_LI
) Correct the file name

**Comment by DragonUncaged** [comment]
> @DragonUncaged Add preview.png

already added preview.jpg

**Review by DEEPALI-SUK — CHANGES_REQUESTED** [review]
In mobile view I am not able to pick colors

**Comment by DragonUncaged** [comment]
> In mobile view I am not able to pick colors

Drag and drop does not work with touch event/ touch screen devices.
That's Why

I have learned this From.
[Mozilla website](https://developer.mozilla.org/en-US/docs/Web/API/Document/drag_event) For the Drag Event in JavaScript And it does Not work in their Website also You Can see

**Review by DEEPALI-SUK — APPROVED** [review]

**Comment by arpit456jain** [comment]
@DragonUncaged  add all colors why its only shades of red ?
and resolve merge conflicts

**Pull request closed without merging**
