### PR TITLE
FIX: issue668 and "click on january is buggy"

### PR DESCRIPTION
**Pull request by BIKRAM-SAHA**
# Description
- Removed bootstrap: Use of bootstrap for just a few classes was a overkill hence removed it.
- Major Changes in the design: mobile responsive too
- Fix new bug:  Fixed-> On selecting January the calendar didn't change which is not the expected behavior.

### **Since this project had a major design change(which took me a while) and I have resolved an extra bug in behavior so I request the this PR to be ranked level 2 or 3**

Fixes:  #668 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [x] I have made this from my own
- [ ] I have taken help from some online resourses 
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK

- image
- image
- image

### CODE REVIEW

**Review by DEEPALI-SUK — CHANGES_REQUESTED** [review]
@BIKRAM-SAHA could you please add one demo video showing both mobile and desktop view and all your changes or please deploy it somewhere and share that link

**Comment by DEEPALI-SUK** [comment]
> @BIKRAM-SAHA could you please add one demo video showing both mobile and desktop view and all your changes or please deploy it somewhere and share that link

as we are having issues with the deployment link

**Comment by BIKRAM-SAHA** [comment]
https://caenderclock.netlify.app/

@DEEPALI-SUK deployment link.

**Comment by BIKRAM-SAHA** [comment]
@DEEPALI-SUK @VidhiBhatt01 Is there any issue with this PR or any suggestions for changes? If not, please mark it `ready to merge`.

**Review by DEEPALI-SUK — APPROVED** [review]

**Pull request merged**
