### PR TITLE
added whack a mole

### LINKED ISSUE #287: Whack a mole
Hey there ! I'm Priyanshi , GSSOC'22 participant, I would like to add whack a mole game to this project. A ss of the game I made is attached. Looking forward to work .
Screenshot (84)

### PR DESCRIPTION
**Pull request by Priyanshi662**
# Description

Added whack a mole game to the project 

Fixes #287 

- [x] New feature (non-breaking change which adds functionality)

# Explain the Testing instructions

**Test Configuration**:

- Text-editors used: sublime text

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by VidhiBhatt01 — COMMENTED** [review]
Copied from here? https://medium.com/@divyamcm/whack-a-mole-game-using-html-css-and-javascript-84b108ec5c8e

**Comment by arpit456jain** [comment]
@Priyanshi662 if u can make some changes to it then only i can accept this.
1. make it responsive
2. move the hammer downwards when we click.

**Comment by Priyanshi662** [comment]
> Copied from here? https://medium.com/@divyamcm/whack-a-mole-game-using-html-css-and-javascript-84b108ec5c8e

No , actually I took some idea from 30 days of javascript wesbos, but I coded this by myself .I didn't knew about this medium article.

**Comment by Priyanshi662** [comment]
> @Priyanshi662 if u can make some changes to it then only i can accept this.
> 
> 1. make it responsive
> 2. move the hammer downwards when we click.

okay give me 1-2 days as my exams are going on, I'll make the changes

**Comment by arpit456jain** [comment]
@Priyanshi662 the hammer is not working plus more than 2 moles  are coming sometimes check it please

**Comment by Priyanshi662** [comment]
> @Priyanshi662 sometimes the hammer is not working plus more than 2 moles are coming sometimes check it please
> 
> the game is good and i will accept it also just improve it a little bit and make PR again when its ready

 I fixed the 2nd issue but for me the hammer is working fine.. please tell me the issue that is happening with hammer .

**Pull request closed without merging**
