### PR TITLE
Sudoku Game:Suggest any improvements/changes

### PR DESCRIPTION
**Pull request by Abhishek786-Kolvekar**
Hello and Good Morning,
Do check my first contribution named Sudoku Game.
Tech Stack: HTML,CSS and JS.

### CODE REVIEW

**Comment by Abhishek786-Kolvekar** [comment]
Key Features:
1. Light and Dark Modes based on user requirements.
2. Difficulty level from Easy to Most Difficult(Inhuman)
3. Good and appealing UI

**Comment by VidhiBhatt01** [comment]
please link the issue in the description

**Comment by Abhishek786-Kolvekar** [comment]
https://github.com/arpit456jain/Amazing-Js-Projects/issues/244
Regards.

**Comment by VidhiBhatt01** [comment]
This looks beautiful! Did you follow any tutorial or made it completely on your own?

**Comment by Abhishek786-Kolvekar** [comment]
I referred to tutorials for CSS on Instagram since I am very weak at it. Rest HTML and JS are my own.

**Pull request merged**
