### PR TITLE
Added ColorCode Converter project files

### LINKED ISSUE #288: Add a Color Code Converter
## Issue Type:

- [x] Feature Request

## **Describe the bug**

Add a color code converter that can change code formats between RGB, Hex, CMYK, & Hsl.

## **Possible solution**

Going to make use of HTML, CSS, & JS.

## **Screenshots**

Capture

### PR DESCRIPTION
**Pull request by XZANATOL**
# Description

A color code converter that converts between RGB, Hex, CMYK & Hsl.
- Conversion from any of the supported formats: RGB, Hex, CMYK, & Hsl.
- User input is validated using Regex.

Fixes #288 

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# Explain the Testing instructions

**Test Configuration**:

- Operating system: Linux, Windows
- Version: Ubuntu, 10
- Text-editors used: Sublime

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK

Capture

### CODE REVIEW

**Comment by arpit456jain** [comment]
changes req
1. implement it naive language colors like i can give input as red,green ,BLUE,YeLLow
2. hex conversion is not working properly chak it again

**Comment by XZANATOL** [comment]
@arpit456jain can you give me the test case you tested the Hex part? I tried multiple combinations and it worked perfectly from my side.

**Comment by XZANATOL** [comment]
@arpit456jain Added colors name support.

**Comment by XZANATOL** [comment]
@arpit456jain Any updates about the review?

**Comment by VidhiBhatt01** [comment]
@arpit456jain I cannot find the project on the deployed link. Can you help?

**Comment by arpit456jain** [comment]
@VidhiBhatt01 
https://deploy-preview-318--amazing-js-projects.netlify.app/color_code_converter/

**Comment by arpit456jain** [comment]
its good now

**Pull request merged**
