### PR TITLE
Added URL Shortner project 

### PR DESCRIPTION
**Pull request by prabhkaur301**
# Description
This project is a URL Shortner made with HTML,SCSS & JavaScript. I used **shrtcode** API for shortening the links. The project UI is like a landing page which is fully responsive.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

- Text-editors used: VS Code

# Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK
# Deployment Link:
 https://prabhkaur301.github.io/Shortly-URL-shortener-web-app/

# Demo Video:- 
https://user-images.githubusercontent.com/57444962/158076363-0bf3629b-cb9e-4f59-acc9-c545b7818c93.mp4

### CODE REVIEW

**Review by VidhiBhatt01 — APPROVED** [review]
It's beautiful. LGTM. @prabhkaur301 did you make it totally on your own?

**Comment by prabhkaur301** [comment]
> It's beautiful. LGTM. @prabhkaur301 did you make it totally on your own?

Yes @VidhiBhatt01 , I completely made this project myself. I got the design reference from one of the FrontEnd Mentor challenge & for URL shortening , I used shrtcode API

**Review by astha2412 — CHANGES_REQUESTED** [review]
Make it more responsive!
Screenshot (409)

**Comment by VidhiBhatt01** [comment]
Oh yeah, @prabhkaur301 it's responsive. You just need to fix the horizontal scrolling.

image

**Comment by arpit456jain** [comment]
@prabhkaur301 the image is making the problem just adjust its width in small screen

https://user-images.githubusercontent.com/55352601/158996741-dd500d4e-fc56-4913-af9a-ba138e6509ab.mp4

**Comment by prabhkaur301** [comment]
I made the required changes to make it fully responsive, it is working fine . Kindly review it

**Review by VidhiBhatt01 — APPROVED** [review]
https://deploy-preview-372--amazing-js-projects.netlify.app/url-shortner/

Good job!

**Comment by arpit456jain** [comment]
@prabhkaur301 remove merge conflicts

**Pull request merged**
