### PR TITLE
Added icon to the Weather App

### PR DESCRIPTION
**Pull request by AvidCoder101**
Just added an icon to the weather app. Please tell me whether you would like me to add icons for the other projects too. Thanks (:

### CODE REVIEW

**Comment by arpit456jain** [comment]
> Just added an icon to the weather app. Please tell me whether you would like me to add icons for the other projects too. Thanks (:

yeah sure why not 

you can ad some projects also there are lots of projects whose source code is available on YouTube
@AvidCoder101  just confirm once whether this PR is under DCP21 or not

**Comment by AvidCoder101** [comment]
@arpit456jain, just a question, what is DCP21?

**Comment by arpit456jain** [comment]
@AvidCoder101 actually its a open source program Devincept which is going to be end today

**Comment by arpit456jain** [comment]
you can join my discord server 
https://discord.gg/gtYUZQSjTt

**Pull request merged**
