### PR TITLE
Random Color Generator

### PR DESCRIPTION
**Pull request by stutimohta20**
# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes:  #655  #660 #679 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [x] I have made this from my own
- [x] I have taken help from some online resourses 
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK

image

# GITHUB REPOSITORY
- https://github.com/stutimohta20/Random-Color-Generator

### CODE REVIEW

**Comment by stutimohta20** [comment]
@VidhiBhatt01 Please check

**Review by VidhiBhatt01 — APPROVED** [review]
This just takes me to the repo. Can't see the deployed version. Anyways, am trusting you and approving this since you have contributed multiple times to our repo.

**Comment by VidhiBhatt01** [comment]
Wait, we already have a random color generator in the repo, didn't you check!?

**Comment by stutimohta20** [comment]
I have been trying to merge this from a long time maybe the other one got approved before @VidhiBhatt01

**Comment by stutimohta20** [comment]
@VidhiBhatt01 @DEEPALI-SUK @arpit456jain  Please merge my pr

**Comment by stutimohta20** [comment]
@VidhiBhatt01 @DEEPALI-SUK @arpit456jain  Please merge my pr

**Comment by VidhiBhatt01** [comment]
PA will merge the PR dw

**Pull request merged**
