### PR TITLE
Added 3rd degree equation solver files

### LINKED ISSUE #388: Third degree equation solver
## Issue Type:

- [ ] Bug Report
- [x] Feature Request
- [ ] Documentaion

## **Describe the bug**

I would like to add a calculator that solves rquations of third degree and prints out its 3 roots (ax^3 + bx^2 + cx + d = 0)

## **Possible solution**

The calculator will be:
* Able to handle complex/imaginary solutions.
* Make use of HTML / CSS / Bootstrap / JavaScript.
* Responsive on desktop and mobile devices.

## **Screenshots**

image

Issue made under GSSoC'22 contributions.

### PR DESCRIPTION
**Pull request by XZANATOL**
# Description

Added a calculator that solves rquations of third degree and prints out its 3 roots (ax^3 + bx^2 + cx + d = 0)
Fixes #388 

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# Explain the Testing instructions

**Test Configuration**:

- Operating system: Ubuntu
- Version: 21
- Text-editors used: Sublime

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK

[Deployment Link](https://htmlpreview.github.io/?https://github.com/XZANATOL/Amazing-Js-Projects/blob/Third_Degree_eq_Solver/Third_Degree_Equation_Solver/index.html)

### CODE REVIEW

**Review by VidhiBhatt01 — CHANGES_REQUESTED** [review]
Make the Box bigger so that it fits the entire screen.

image

image

**Comment by XZANATOL** [comment]
@VidhiBhatt01 Done.

**Comment by VidhiBhatt01** [comment]
Still the same.

image

Align it in center too.

**Comment by XZANATOL** [comment]
@VidhiBhatt01 Done.

**Comment by VidhiBhatt01** [comment]
Almost perfect, can we do center alignment too?

**Comment by XZANATOL** [comment]
I don't quite grasp what you mean. It's already center aligned

**Comment by VidhiBhatt01** [comment]
> I don't quite grasp what you mean. It's already center aligned

Just drop a DM on discord, will help you out tomorrow over a quick 5 min call.

**Comment by XZANATOL** [comment]
Sure.

**Comment by arpit456jain** [comment]
@XZANATOL any updates

**Comment by XZANATOL** [comment]
@VidhiBhatt01 Done.

**Review by VidhiBhatt01 — APPROVED** [review]

**Comment by VidhiBhatt01** [comment]
@XZANATOL it's done, just add this project in style_links.json

**Review by arpit456jain — APPROVED** [review]

**Pull request merged**
