### PR TITLE
Random Image Feed

### PR DESCRIPTION
**Pull request by Khushi-Mattu**
# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes:  #(issue no.)
#662

## Type of change

- [x ] New feature (non-breaking change which adds functionality)

# Checklist:

- [x ] I have taken help from some online resourses 
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK
image
After Refreshing
image

### CODE REVIEW

**Review by VidhiBhatt01 — CHANGES_REQUESTED** [review]
Link issue properly and remove extra files

**Comment by Khushi-Mattu** [comment]
what do you mean by link issue properly?

**Review by VidhiBhatt01 — CHANGES_REQUESTED** [review]
You need to link the issue as #Number and not just Number. Also remove extra files from the PR

**Comment by Khushi-Mattu** [comment]
Done

**Comment by DEEPALI-SUK** [comment]
https://deploy-preview-673--amazing-js-projects.netlify.app/random%20image%20feed/

**Review by DEEPALI-SUK — COMMENTED** [review]
https://github.com/CrazyCoding21/CC-JavaScript-29-Random-Image-Feed

https://www.youtube.com/watch?v=Z5z2nWp4QwY

**Comment by Khushi-Mattu** [comment]
look @DEEPALI-SUK this project is obviously not some out of the box project but I did make it myself. You ll find 100s of random image feeds online. But more than 50% of the projects in this repository can be found on the internet. This is just amusing.

**Review by VidhiBhatt01 — CHANGES_REQUESTED** [review]
You need to make some changes, we cannot accept the same code

**Comment by Khushi-Mattu** [comment]
The code isnt same, only the result is. And obviously the logic between the codes would be same because I mean that is the logic But anyway upto you! 
Good luck :)

**Comment by VidhiBhatt01** [comment]
Bruh, who are you trying to fool? We have reviewed more than 150 PRs in this repo over the last 2 months. Changing the margin, height, and width does not make the project different. Rest all is totally the same. But hat's off to your confidence! Salute.


And yeah, don't worry we will make sure only valid contributions are counted. We will remove all the plagiarised ones. If you find any, you can send those PRs to us over discord DM

**Comment by Khushi-Mattu** [comment]
why you getting worked up lmao

**Pull request closed without merging**
